### ISSUE TITLE
Route level permissions for Custom APIs

### ISSUE THREAD

**Issue by jtmilne** [Azure/azure-mobile-apps-node#102]
In the current Mobile Services implementation of Custom API permissions are set at the verb level for the entire controller. That makes sense for Tables (where each verb is unique for that controller) but was problematic for Custom APIs where each controller can have multiple routes with the same verb. For example in the current Mobile Services if you have:

	api.get('/:id', getUser);
	api.get('/', getUsers);

you cannot set different permission levels for those 2 routes (as far as I know). You have to create 2 controllers for the same resource to implement different permission levels for the same verb.

It would be great if permissions could be set at the route level in the new SDK with a standard middleware pattern. Something like this would be ideal:

	exports.register = function(router)
	{
		router.get('/:id', [api.authorizeApplication, getUser]);
		router.get('/', [api.authorizeUser, getUsers]);
	};

**Comment by phvannor** [comment]
in Node.js v1 you can customize the json to configure permissions in detail, like so:
{
	"routes": {
		"/": {
			"permission" : "application"
		},
		"/getDepartment" : {
			"permission" : "user"
		},
		"/getAllDepartments" : {
			"permission":"application"
		},
}

**Comment by jtmilne** [comment]
Great. I assume that structure above also has a verb level as well? e.g.

	{
		"routes": {
			"/": {
				get: {"permission" : "application"},
				post: {"permission" : "application"}
			},
			"/getDepartment": {
				get: {"permission" : "user"},
				post: {"permission" : "user"}
			}
		}
	}

Although it would still be a whole lot easier (and much more maintainable) to specify the permissions as middlewhere when registering the route rather than having to maintain the routes in one file and then create permissions in a separate json file.

**Comment by phvannor** [comment]
Yes inline can be easier to configrue for v2 and I believe that's the plan here.

For v1, yes you can use verb as well, here's another example of routes in v1: http://stackoverflow.com/questions/27685908/permission-on-multiple-routes-in-a-custom-api-for-an-azure-mobile-service

**Comment by jtmilne** [comment]
Thanks for the clarification.

In that case, I would clarify this feature request as being the ability to add permissions inline while registering routes.

**Comment by danderson00** [comment]
Unfortunately, we won't be adding this feature, given how easy it is to mount express routers to achieve the same functionality and taking into account plans.
