### ISSUE TITLE
Support JS cross window messaging for authentication flow

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-node#139]
As part of EasyAuth enablement for JS, we need the old login receiver page to be returned from the server SDK (the portion that does the postMessage() calls)

If IE8/9 is also included, we will need to talk about also serving the old bridge as well.

**Comment by danderson00** [comment]
No worries, I suspected this would be the case. My understanding is that we won't support IE8/9, at least for now. I suggest we drop it unless it is specifically requested.

**Comment by adrianhall** [comment]
I'm ok with this limitation.  Let's explicitly document this as part of the API docs as well as in the README in the checkin.

**Comment by danderson00** [comment]
I actually ended up adding the bridge anyway, it was no extra effort.

**Comment by danderson00** [comment]
This will be handled by Azure Web Apps authentication
