### ISSUE TITLE
Support MS_SkipVersionCheck for enabling/disabling version check

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#141]
The .NET SDK has an app setting for MS_SkipVersionCheck - we should use the same for node.  (Ref: #90)

**Comment by danderson00** [comment]
Resolved

**Comment by phvannor** [comment]
Dale can you link the commit like 889b9524a8c5b8311919374b21be3cd4f436a702 or when its a PR just link to the issue from there :smile:

**Comment by danderson00** [comment]
I have been linking PRs but not commits. Will link commits from now on.

Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/889b9524a8c5b8311919374b21be3cd4f436a702
