### ISSUE TITLE
Deep-assign module incorrect merges configuration 

### ISSUE THREAD

**Issue by fduch2k** [Azure/azure-mobile-apps-node#145]
```js
var assign = require('deep-assign');
var result = assign({data: {provider: 'memory'}}, {data: {provider: function() {}}});
console.log(result);
```
Output is:
```
{ data: { provider: [String: 'memory']}
```
instead of:
```
{ data: { provider: [Function] } }
```

**Comment by danderson00** [comment]
Hmm... We've had some problems with deep-assign already. I'll look for an alternative that behaves how we'd like.

**Comment by fduch2k** [comment]
May I suggest lodash.merge? It also can replace underscore and underscore.strings modules

**Comment by danderson00** [comment]
Added some unit tests around merge / assign functionality that assert our requirements. lodash's merge function does pass these tests, but we already have a dependency on underscore (temporary - the query modules will be extracted out into their own package soon). We may revisit this during refactoring down the track.

**Comment by fduch2k** [comment]
Currently, it cannot works with custom data provider. For me it's show stopper

**Comment by danderson00** [comment]
I replaced deep-assign with deeply. This should resolve your issue.
