### ISSUE TITLE
Refactor data integration tests to enable execution against all providers

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#150]

**Comment by danderson00** [comment]
Only really needed for GA if we plan to have the SQLite provider ready as well. We may also wish to do this to better enable community contributed providers.

**Comment by adrianhall** [comment]
It was the community providers that I wished to enable.  I'm ok with it being a P3 for GA - we can push it out if needed, but I'd rather see it in given the runway to GA.
