### ISSUE TITLE
Implement .auth endpoint stub for local development

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#152]
Requires substitution of push notification and authentication middleware with appropriate stubs, as well as https://github.com/Azure/azure-mobile-apps-node/issues/50.

**Comment by joewood** [comment]
Is there an open issue tracking local authentication (or remote authentication redirected to localhost #275)? Is this planned for version 2?

**Comment by danderson00** [comment]
This issue is intended to track it.

**Comment by joewood** [comment]
Is there a workaround where I can login with a facebook token using client style authentication against the cloud based URI (i.e. using the FB SDK), then redirect to localhost with the zumo token? Is this possible now?

**Comment by danderson00** [comment]
A colleague was asking the same thing today. Apparently it is possible to set the client to use a cloud based auth endpoint (the .auth endpoint on a web app) but have the mobile app URL still set to localhost. You then need to get the WEBSITE_AUTH_SIGNING_KEY app setting from your kudu endpoint (https://mobileApp.scm.azure-websites.net/) and assign this to the auth.secret config option.

I'm not 100% sure the exact way to configure the client, and it will depend on which client platform you are using. Let me know if you need help, I can ping my colleague and how they went.

**Comment by joewood** [comment]
Yes, I did the `auth.secret` configuration. I'm stuck in how to convert a Facebook (or other) auth token to a zumo token using that secret.  If I run locally and use the `.login("facebook", token)` after Facebook login from a Single Page Webapp the MobileServices.Web.js tries to access `localhost/.auth/login/facebook` but that responds in a **404**. So I suspect this isn't supported (I haven't tried this on the server yet).

Looking at the tests here: [azure-mobile-apps-js-client/winJS/tests/unit/mobileServicesClient.js#L79]( https://github.com/Azure/azure-mobile-apps-js-client/blob/f8469065199e6314e4c85c8f1699ee87ea32cd2b/sdk/test/winJS/tests/unit/mobileServicesClient.js#L79) it looks like this approach may be wrong.

Any help here would be appreciated.

**Comment by danderson00** [comment]
A client flow is not yet supported. You can set the alternateLoginHost property on the mobile app client to point it at a hosted site to get the token. You may also need to set the auth audience and issuer values in the auth configuration. We'll provide a much smoother experience soon!

**Comment by joewood** [comment]
OK, sounds like it's not ready yet. Is there a time frame when 2.0 will have parity with v. 1?

**Comment by joewood** [comment]
Just to be clear about "client flow" not being supported. Does that mean mobile authentication using native integration (e.g. the Facebook app) isn't supported yet either?

**Comment by danderson00** [comment]
What client platform are you using? Cordova or web? We'll be releasing a Cordova client in January, but the web client still requires testing and some work to make login flows reliable. The Node SDK will also GA at the end of January.

By "client flow", I mean the client obtains a token from the auth provider, e.g. facebook, and hands this token to the Login function on the client - this translates the facebook token into a Mobile Apps token. This should be supported for some scenarios, but is largely untested in a browser.

**Comment by joewood** [comment]
Hi Dale - this is Web, but logging in separately using Facebook. And also iOS, again using native FB login. 

Yes, client flow where the token is obtained separately. If this scenario is supported for Cordova wouldn't it be the same code for the Web SPA?

**Comment by shrishrirang** [comment]
@joewood: "Server flow" and "Client flow" both will be supported in the next release (beta3) of the Cordova client. After that client flow for javascript in browser should just work too but we haven't tested it. Server flow will not work though as the browser (and Cordova running in Ripple environment) and Cordova code paths are different. Again, once server flow is fixed for Cordova in Ripple environment, it should work in browser too.

**Comment by joewood** [comment]
Thanks @shrishrirang 
Is the code base from the Cordova client synchronized with the JS client? Are these actually just the same code? Happy to help testing the Client Flow for any of the platforms. I'm using the iOS SDK via React Native too.

**Comment by shrishrirang** [comment]
The code for Cordova and browser is pretty much the same (https://github.com/Azure/azure-mobile-apps-js-client). As of today, the Cordova plugin simply packages the browser bundle (https://github.com/Azure/azure-mobile-services-cordova/blob/MobileApp/www/MobileServices.Web.js) with a few other files.

**Comment by joewood** [comment]
Just a quick update on trying the `alternateLoginHost` approach. This redirects to the cloud for authentication but doesn't fire the callback for login complete. The redirect through the provider's login dialog box redirects to the hosted environment. Overriding the `endUri` in the client API (in the code) for `Platform.login` to be the **localhost** service doesn't seem to work either.

**Comment by danderson00** [comment]
A note on the alternateLoginHost approach - this will work when EasyAuth implement the postMessage functionality for notifying parent windows of login completion (similar to how V1 worked). This is being implemented.

As far as .auth stub, there are a few scenarios we need to cater for:
- postMessage to parent window to notify login complete
- redirect to .auth/login/done with token in querystring
- client flow posts token to .auth/login/provider endpoint

**Comment by danderson00** [comment]
Oh... And this won't work for Windows Store apps. The WebAuthenticationBroker approach used by the managed client simply does not work with localhost URIs.

**Comment by danderson00** [comment]
This also currently requires running the local server over HTTPS, i.e. generating a key and certificate, installing certificate to trust it and configuring the app to listen on HTTPS instead of HTTP. It's feasible to remove the limitation from the client, but there may be other platform issues with auth over HTTP.

**Comment by danderson00** [comment]
Above scenarios *should* work, though client flow won't work on localhost for most platforms anyway. 

Remaining tasks:
- Make user returned configurable
- getIdentities stub
- Test/retest all platforms

It's worth mentioning that this will remain a beta feature on GA.

**Comment by joewood** [comment]
Before GA - can a callback be added to the configuration.auth to cover the custom user object and auth response? A custom `getIdentity` is already supported on the config.

**Comment by danderson00** [comment]
Callback added in https://github.com/Azure/azure-mobile-apps-node/commit/675e3fc9dd6834e937de291c214fe2cd99e43cb6. Closing this issue.
