### ISSUE TITLE
JsDocs: Make "Global" category the top category for the left-nav

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-mobile-apps-node#156]
**Description:** The Global object contains a lot of critical, important information for configuration, but it's down at the bottom of the left nav. 

**Impact:** Important information is often overlooked.

**Suggested Improvement:** Up leveling it to the top will increase visibility.

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/012c66d74bbf03fc0e17c199d4ca9991c900807b
