### ISSUE TITLE
Remove MS_SigningKey as a mechanism for setting the JWT Signing Key

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#172]
The Gateway used MS_SigningKey.  The new auth uses WEBSITE_AUTH_SIGNING_KEY.  We are not going to support the gateway going forward.

**Comment by danderson00** [comment]
Resolved by direct edit / commit https://github.com/Azure/azure-mobile-apps-node/commit/e987d2c7f3d407efb450d02f24956e08fecdcd7a
