### ISSUE TITLE
On launch, should check for tables already created

### ISSUE THREAD

**Issue by Mimetis** [Azure/azure-mobile-apps-node#175]
Once the tables are created, maybe test if tables already exists. Raising an error is processor consuming and performance are affected

on Triggers : 
```sql
sql: 'IF NOT EXISTS (SELECT * from SYS.TRIGGERS WHERE NAME = \'' + triggerName + '\') 
EXEC(\' CREATE TRIGGER [' + triggerName + '] ON ' + tableName + ' AFTER INSERT, UPDATE, DELETE AS 
BEGIN 
SET NOCOUNT ON; IF TRIGGER_NESTLEVEL() > 3 RETURN; 
UPDATE ' + tableName + ' SET [updatedAt] = CONVERT (DATETIMEOFFSET(3),
SYSUTCDATETIME()) FROM INSERTED WHERE INSERTED.id = ' + tableName + '.[id] 
END \')'
```
on Tables

```sql
sql: 'IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = \'' +  tableConfig.name + '\')
        CREATE TABLE ' + tableName + ' (' + columnSql + ') ON [PRIMARY]'
 ```

On Indexes : 

```sql
sql: 'IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = \'' + indexName + '\') 
       CREATE INDEX [' + indexName + '] ON ' + tableName + ' (' + columnsString + ')'
```

**Comment by danderson00** [comment]
This is a one time penalty at startup. This is additional complexity that likely won't get implemented.

**Comment by Mimetis** [comment]
Ok, but in my opinion, raising an error is most disadvantageous

**Comment by danderson00** [comment]
I agree it is not the cleanest approach. The schema creation is based off the dynamic schema approach where inserting an item for the first time creates the table when a specific SQL Server error occurs. Checking for the existence of the table each time a row is inserted would incur a significant performance. Having said this, we could add the check just for the startup initialize, but I can't see any real benefit at this stage.

**Comment by Mimetis** [comment]
Ok, make sense :)

Can you, maybe, add this verification on the initialize() method, after the create table step ?

In this case, we sould have two sql statements for each "Create Table", "Create Trigger", "Create Index" steps.
One statement with the schema verification, used during the initialize step, and one without, used every times, which can handle the dynamic schema approach.

In my very own opinion, using errors to handle business rules is a bad idea :)

**Comment by danderson00** [comment]
You make a good point. Will reopen the issue for potential implementation down the track.

**Comment by danderson00** [comment]
You are totally right. Logging output with level set to debug is nasty with the current approach. We'll address this before a stable release.
