### ISSUE TITLE
Provide guidance on setting up /swagger and /swagger/ui endpoints

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#205]
The .NET Backend for Azure Mobile Apps has a /help endpoint for an API explorer.  Add the same thing for the NodeJS backend.

**Comment by adrianhall** [comment]
This will be resolved when we implement Swagger - #68

**Comment by danderson00** [comment]
Well... It won't be resolved now it's clear what is required

**Comment by danderson00** [comment]
With the above PR, this is now just a matter of providing guidance, probably through samples. Essentially:

    mobileApp = mobileApps({ swagger: true })

for the /swagger endpoint and then

    npm i swagger-ui --save

for the /swagger/ui endpoint.

**Comment by danderson00** [comment]
@adrianhall We could also just include swagger-ui as a hard dependency so the user doesn't need to install it, but our dependency list is already pretty long. What do you think?

**Comment by adrianhall** [comment]
Added in azure/azure-content-pr#19246
