### ISSUE TITLE
Using configuration should not assume object exists

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-node#212]
In the fromConfiguration line, assumptions are made about the config object being passed in like so:
https://github.com/Azure/azure-mobile-apps-node/blame/master/src/configuration/fromEnvironment.js#L70

We should either be explicit on validation (so user gets a nice message that auth : { } is required, or handle the object (auth, data, etc) not being defined in config correctly (i.e. just create it)

**Comment by danderson00** [comment]
I'm going to close this issue. This initialization is necessary for now due to previous wrangling with variations of the assign function. We have a larger task to refactor our configuration story.
