### ISSUE TITLE
Return 500 when GET /tables/x and x does not exist

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#22]
When you do a GET /tables/x and x does not exist as a table, we return an empty set - we should return a 500 indicating the table does not exist yet.

**Comment by adrianhall** [comment]
To be specific, this is when the table has been defined in configuration but the table does not exist in the underlying database (i.e. dynamic schema turned off)

**Comment by danderson00** [comment]
This already appears to be the case. Added a test in https://github.com/Azure/azure-mobile-apps-node/commit/1c87ef16cf3c29f8dd16e4b00f465c9edb322b1c
