### ISSUE TITLE
Update samples to protect update and delete operations

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#228]
Only allow updates and deletes to records the user "owns", i.e.:

	table.delete(function (context) {
	  context.query.where({ userId: context.user.id });
	  return context.execute();
	});

Dependent on https://github.com/Azure/azure-mobile-apps-node/issues/227

**Comment by adrianhall** [comment]
Pull request #329 issued for samples update.  This can be closed when merged.
