### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by justin** [Azure/azure-mobile-apps-node#232]
We are using TypeScript for our Azure Mobile Apps project. Doesn't seem to be an official TSD. Would be nice if that was a thing.

**Comment by danderson00** [comment]
We've had considerable discussion about this recently. As we currently use jsdoc for API reference documentation, we want to find a way to either generate the same documentation from the TSDs, or visa versa, i.e. avoid having to maintain both jsdocs and TSDs. We do intend to provide these!

**Comment by jocull** [comment]
+1

**Comment by joewood** [comment]
+1 for client and server side components

**Comment by danderson00** [comment]
require('azure-mobile-apps').table() does not work

**Comment by danderson00** [comment]
There are .d.ts available in the typings folder. You'll need azure-mobile-apps and azure-sb as well as express.d.ts from DefinitelyTyped. I've submitted a pull request for adding these to the repository. Tracked in https://github.com/Azure/azure-mobile-apps-node/issues/309

**Comment by Ross-Rawlins** [comment]
any news on this?
