### ISSUE TITLE
NH Registration Tag Support

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-node#241]
We need to restore the ability to have the client able to send tags along to the server (and be approved)

In v1, we allowed a code hook to allow developer to customize / reject generate tags.

Possibly a white/blacklist could work for the simple case if its easier as a workaround.

Original issue found in: Azure/azure-mobile-services#762 (comment)

**Comment by phvannor** [comment]
.Net server copy: https://github.com/Azure/azure-mobile-apps-net-server/issues/36

**Comment by danderson00** [comment]
I thought the decision was to not allow this for security reasons? Was there another decision made around this? We need to ensure the semantics are equivalent between platforms.

**Comment by phvannor** [comment]
The security concern is having the client able to send unvetted tags at will.  If the server has a hook that lets the dev vet each tag before being sent on to the NH, than we are ok with letting tags come up.  Plus a hook allows the dev to tack on any custom tags they may want for business logic w/o forcing another round trip/etc on their client app.

**Comment by wesmc7777** [comment]
We also have customers asking for this..

https://acom-prod-uswest-01.azurewebsites.net/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-push/#comment-2385013302

**Comment by wesmc7777** [comment]
Another customer comment regarding this here...
https://azure.microsoft.com/en-us/documentation/articles/notification-hubs-overview/#comment-2415780828

**Comment by adrianhall** [comment]
This will be covered by Aziel's work on the Push Registration Server.  It won't be added to the server SDK.

**Comment by danderson00** [comment]
Woot!
