### ISSUE TITLE
CORS Preflight (OPTIONS /tables/blah) always fails with 400

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#242]
Doing a CORS request results in a pre-flight check, which always fails with a HTTP Response 400.

This happens when running the server locally (node --debug server.js) and in Azure Portal.

**Comment by phvannor** [comment]
Isn't this on purpose?  I thought until a general CORS setup is offered for all Web Apps via the portal, any  CORS setup needs manually configured in the server bits by the developer?

Or is this a request to stop gap just the QS until the above work happens?

**Comment by danderson00** [comment]
We are aiming at parity with V1 for now. It's all there, just needs a couple of fixes. I was not aware that Web Apps was going to introduce a generic CORS solution.

**Comment by phvannor** [comment]
We took out all the CORS baked in stuff for .Net, what does Parity mean here?

**Comment by danderson00** [comment]
V1 handled CORS exclusively

**Comment by phvannor** [comment]
In my discussion on the JS SDK & CORS (since this is blocking a GA of JS SDK) we said we wait on Web Apps or dev's can set it up manually in the meantime.  We should sync up before adding back MS_CrossDomainWhitelist/etc.

**Comment by danderson00** [comment]
It's already implemented. CORS is a bit of a pain for developers to set up themselves. It's a very small piece of middleware that can be easily removed.

**Comment by phvannor** [comment]
Yeah, but EA will requires it own setup, so I think we want to be careful how much help we provide and that it ends up playing nicely with the final setup required to use auth as well.
