### ISSUE TITLE
Make CORS work when running locally (i.e. developer mode)

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#245]
Azure App Service handles CORS explicitly through the Settings -> CORS options.  When running within Azure App Service, the SDK should not do any CORS handling, delegating that functionality to the App Service.

If the server is running locally in development mode, CORS should "do the right thing" - likely allowing localhost:*.  This will allow the user to develop locally without the server getting in the way.

Ideally, there would be an option to enable CORS handling that is loaded from azureMobile.js.  CORS handling would be disabled by default (since the App Service environment is the default)

**Comment by adrianhall** [comment]
Ref azure-mobile-apps-net-server#38

**Comment by danderson00** [comment]
This should work with CORS configuration in azureMobile.js. Will test and close if it works correctly.

**Comment by joewood** [comment]
I'm seeing CORS errors running locally. Has this been fixed and is it in the GA build and not the "2.0.0-beta1" build?

**Comment by danderson00** [comment]
Hmm.. This should work, though I haven't tested comprehensively when running locally. What errors are you seeing? Are they on the browser or on the server? We also need to add more verbose logging / tracing to these sorts of areas.

**Comment by joewood** [comment]
Yes, it works from **master**. It must have been fixed after the beta1 was released.

**Comment by danderson00** [comment]
We will introduce some form of change log based on github issues from here on in, though that won't help with knowing what's unreleased in master. We'll look at having some sort of issue query that you can use to see what's implemented but not yet released.

**Comment by danderson00** [comment]
Verified that this works out of the box with zero configuration when running from localhost.

**Comment by danderson00** [comment]
https://github.com/danderson00/ama-cors-sample
