### ISSUE TITLE
Produce yeoman generator for Mobile Apps Server

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#257]
Need a generator-azure-mobile-apps package to produce a prototypical Azure Mobile Apps skeleton.

**Comment by danderson00** [comment]
Can you elaborate? What problem does this solve?

**Comment by adrianhall** [comment]
"As a Javascript developer, I want to generate the boilerplate code for an Azure Mobile App through code generation"

Two solutions:
1) yeoman generator (for those customers who DONT use Visual Studio)
2) VS project (for those customer who do use Visual Studio)

This is #1.

**Comment by danderson00** [comment]
Hmm... I'm not convinced. To spin up a functional app with one table, it's five short lines of code - four lines of boilerplate.

**Comment by adrianhall** [comment]
I've made an initial cut in https://github.com/adrianhall/generator-azure-mobile-apps and published to npm to see how popular it will be.

It's not just the app - it's also advice on testing, documentation, etc.  It's recommending a canonical way of producing the app.

**Comment by danderson00** [comment]
Remember that if we make this an official part of the product, we need to ensure that it works reliably and is maintained. In my mind, this requires automated tests as part of the build. Testing this is a little different to normal unit tests and would take some time to set up. There is a non-trivial amount of effort in this piece.

Traditionally, this kind of guidance has been provided in tutorials, and plus we have many samples. Let's keep it in your repo for now and see if it is used.

**Comment by danderson00** [comment]
See external repo. Closing.
