### ISSUE TITLE
Rename cors.origins configuration property to cors.hostnames

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-node#288]
I had a problem authenticating the origin for CORS testing. I noticed that the final Regex on this line: [src/cors/index.js#L85](
https://github.com/Azure/azure-mobile-apps-node/blob/8f83916833fbd3e68ae8ce2c3932402665a5cdd2/src/cors/index.js#L85) tested against the origin's hostname and not the full origin, which is what the built regex assumes.

**Comment by joewood** [comment]
Also, is this config being picked up from the portal? It doesn't seem to be. Even with a `"*"` entry.

**Comment by adrianhall** [comment]
The CORS in the portal overrides the CORS in the app.  The CORS settings in the app are only there for local development.  If you wish to use the CORS settings in the app when it is deployed to Azure, do not configure CORS in the portal.

**Comment by danderson00** [comment]
We will likely recommend using the portal to configure CORS. Azure Web Apps provides CORS functionality, we would just need to allow configuration of a CORS "stub" middleware for local development.

**Comment by joewood** [comment]
The portal setting doesn't seem to have any effect. I'm setting cors, even to `*`, and still seeing cross domain errors for HTTP POSTs to `.auth/login/facebook`. It works fine when running from the same origin.

**Comment by phvannor** [comment]
I thought there were pending issues with the allowed headers/etc fields that we needed fixed in the portal version of CORS yet?  Have those been addressed / did those not impact the login flows?

**Comment by danderson00** [comment]
@phvannor You're right, I don't think the issue has been resolved, i.e. Azure Web Apps strips all the Access-Control headers from responses and adds its own. The consequences in the meantime are that we have to use the portal to configure CORS and that etag and link headers won't be visible to the client. I'll chase this up tomorrow.

@joewood As far as the original issue goes, the unit tests are the source of truth - have a look at https://github.com/Azure/azure-mobile-apps-node/blob/master/test/cors/cors.origin.tests.js. Does this answer your question and resolve the issue?

As far as the .auth endpoint goes, I kind of assumed CORS just worked, but maybe not. I'll try to repro tomorrow.

**Comment by danderson00** [comment]
It's worth pointing out that the original agreement with Web Apps was to only allow the Access-Control-Expose-Headers header through from apps to allow the client to access custom headers. When hosted, the portal configuration would be the source of truth and override the app configuration. It's questionable as to whether the current implementation will even remain. For local debugging, we could just add a simple piece of middleware to allow all requests.

**Comment by joewood** [comment]
@danderson00 the CORS tests list just the hostname pattern in the origin array. That's fine, it was just confusing that the regex builder seemed to accommodate for full URLs and the portal lists URLs. Plus, strictly speaking, an origin does include the port. Not a big deal, just might be clearer if it was called "hostnames" or something.

On the CORS bug when running in the hosted environment. This may be just an issue with the POST on `.auth/login/facebook`. Not sure if this is a special case for websites, but it seems to ignore the portal configured CORS origin list.  Right now it's prevented client driven login when running the client side outside the hosted environment (i.e. debugging the client side).  So, a bit of a show-stopper for development work.

**Comment by danderson00** [comment]
@joewood I can repro the issue when hosted and have pinged the auth team. Will keep you posted on fixes / workarounds.

Point taken on the config name, it should really be hostnames. I'll add this as an issue. I'll be making it so that the CORS middleware is only loaded when running locally as well.

**Comment by danderson00** [comment]
Actually... This is the issue to track the hostnames property rename... hehehe...

**Comment by joewood** [comment]
Great, thanks @danderson00 
With this problem, along with server driven login not working, it's making it very hard to develop against a Mobile Service from a browser SPA. At the moment any changes have to be deployed to be tested. Any workarounds to any of these issues would be appreciated.

**Comment by danderson00** [comment]
I have an experimental local auth stub at https://github.com/danderson00/azure-mobile-apps-node/tree/authStub. It should just work with a SPA if both are hosted on localhost, though I've only tested it on the same origin. It *only* works with a SPA, and maybe cordova, haven't worked other platforms out yet.

I also had a client flow with the Live SDK working, but client and mobile app were hosted on the same orgin, CORS is still an issue. I will organise a meeting with the auth and cors devs tomorrow.

**Comment by joewood** [comment]
Thanks @danderson00 
I've played with this a bit. I had to change the authStub response to send back the `envelope.oauth` rather than the script to close the window. I'm using client directed login and the client SDK is just POSTing the token to the /.auth/login/:provider.  

That seems to work. But now I'm hitting a strange CORS issue. The CORS middleware is enabled and works for non-table queries. For some reason it's not working for table queries. Maybe there's a missing `next()` call somewhere in the table middleware, because other diagnostic middleware added after the mobile app set-up isn't being called either.  It seems any express app `.use` after the mobile app set-up isn't being called for table queries.

**Comment by danderson00** [comment]
Pretty sure this was my mistake - I changed the order in which middleware was being mounted so the the CORS middleware was being loaded after tables and custom APIs. I haven't tested, but the change is in this commit https://github.com/danderson00/azure-mobile-apps-node/commit/5c3aa554e2224589a0a38e986026e46b9e55c278. I had to readd the authenticate middleware into be loaded in all cases so the token is decoded when hosted.

**Comment by joewood** [comment]
That fixed it. It works OK now using client directed login (I haven't tested alternativeLogin yet).  I had to do a couple of things to get it working:
* I had to stash away the original token (from Facebook in this case) into the config object when the authStub is invoked. For some reason there's no body parser in the middleware for the auth endpoint.
* I had to add my own `getIdentity` function to the config file. I use this to reflect back the original auth token so it can be used to get extended identity information (e.g. FB open graph call).
* I'm also sending back the auth token directly rather than the close window script, as mentioned above, in the authStub in response to the POST to `/.auth/login/<provider>`

I still think there's something odd going on with the middleware chaining, as adding middleware after `app.use(mobileapp)` doesn't seem to work. Minor issue now though.

Thanks for your help.

**Comment by joewood** [comment]
Incidentally, I didn't have to go the HTTPS route to run everything from localhost. I guess I would need to for server login with the altlogin url.

**Comment by joewood** [comment]
@danderson00 could you add a way to override the authStub with your own version so that we can return a test identity? Right now you can only customize the `authStubRoute`, and therefore provide your own middleware, but there's no way to override the authorization URL from the client API (so this isn't too useful) - e.g. you can't change URL that the client POSTs from `/.auth/login/<provider>` to `/.my_auth/login/<provider>`.

To workaround this right now I'm configuring a fake `authStubRoute` in the config e.g.:
```javascript
   authStubRoute:"/.auth/fake/:provider",
``` 
and then adding a manual middleware custom stub to the conventional URL.
```javascript
  var authStub = require("./my-authstub")(mobileApp.configuration);
  app.use("/.auth/login/:provider",authStub);
```

This works OK, but it would be better to simply add new configuration field to customize the auth stub with a function rather than the route.

**Comment by phvannor** [comment]
@joewood you can configure the client API being used via the login prefix (see: https://github.com/phvannor/azure-mobile-apps-net-client/blob/master/sdk/src/Microsoft.WindowsAzure.MobileServices/IMobileServiceClient.cs#L35)  

By default its .auth/login, but you could easily say client.loginPrefix = ".my_auth/login" instead.  

The idea is you normally use .loginHost to point to the cloud during local debug (so login still hits EA at yourapp.azurewebsites.net) but between the two you can control everything but the :provider: and done portions of the URL.

**Comment by joewood** [comment]
Hi @phvannor yes, I tried that. The field is called "loginUriPrefix" I think. But it looks like the client API only uses that for the dialog and not when you have a token. Used here:
https://github.com/Azure/azure-mobile-apps-js-client/blob/f05beb09b6dccb23fb155ef6abbdcd32a44098ad/sdk/src/MobileServiceLogin.js#L427

And not used here:
https://github.com/Azure/azure-mobile-apps-js-client/blob/f05beb09b6dccb23fb155ef6abbdcd32a44098ad/sdk/src/MobileServiceLogin.js#L381

**Comment by phvannor** [comment]
Ouch, that is a very bad bug :(  It is supposed to use it for both...

**Comment by phvannor** [comment]
https://github.com/Azure/azure-mobile-apps-net-client/issues/64 to track, sorry loginPrefix is the property name in iOS, I thought I caught myself.

**Comment by phvannor** [comment]
Sorry wrong repo there, https://github.com/Azure/azure-mobile-apps-js-client/issues/67 thats the right one now...

**Comment by danderson00** [comment]
@joewood Adding a configuration parameter authStubClaims that allows you to customise the JWT token payload. It's in https://github.com/danderson00/azure-mobile-apps-node/tree/authStubClaims. Will merge early next week.

**Comment by joewood** [comment]
Thanks @phvannor. The problem is that a custom auth route doesn't really help out of the box, because it still uses the hardcoded `authStub` and not a custom callback. So even when https://github.com/Azure/azure-mobile-apps-js-client/issues/67 is fixed, I'll still need a callback.

Thanks @danderson00, as well as customizing the payload it would be really useful to have a callback. Right now I propagate the access token on the auth object so that it can be used by `getIdentity` as a token store:
 
**In my stub, before sending:**
```javascript
   configuration.auth.facebook = req.body.access_token
   res.status(200).send( envelope.oauth);
```
In my **configuration azureMobile.js**
```javascript
  auth: {
        secret: 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
        getIdentity: function (config, token, provider) {
            return new Promise(function(c,e) {
                c( { accessToken: config[provider] });
            });
        }
    }
```
