### ISSUE TITLE
No debugging output when api function crashes

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#330]
Given the following api/config.js:

```
import config from 'config';
import { logger } from '../logger';

logger.trace('api/config.js#init: Loaded api/config.js');

/**
 * Handler for GET /api/config
 * Returns the JSON client configuration
 * @param {express.Request} request the ExpressJS Request object
 * @param {express.Response} response the ExpressJS Response object
 * @returns {express.Response} response the result of the operation
 */
function getConfiguration(request, response) {
    logger.trace('api/config.js#getConfiguration');

    let clientConfiguration = {
        auth: {
            endpoint: config.get('auth.endpoint')
        }
    };

    logger.trace('api/config.js: config = ', JSON.stringify(clientConfiguration));

    return response.status(200).type('application/json').send(clientConfiguration);
}

// Define the API
let api = {
    get: getConfiguration
};

// Specify options to the API
api.get.access = 'anonymous';

// Export the API
export default api;
```

This shows an error in the logging when the server is run.  However, when you remove the logger.trace in the main body (leave the ones in the function), it fails silently.  logger.trace does not exist (which is what introduces the error).

We need to log an appropriate failure message when an API is loaded but the function causes a runtime error.

**Comment by danderson00** [comment]
So, the kicker is that this doesn't actually crash. As the module exports is now { default: { blah } }, it just doesn't create any routes as the loader is looking for properties like get, post, patch, etc. I'll add logging to warn that no routes were added.

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/72f541d2bdc6796f55bf008df58e17ad341d72a6
