### ISSUE TITLE
Support ES2015 Modules in import

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#331]
When you are using ES2015 modules, the following line (equivalent to `module.exports = api`):

```
let api = {
    get: somefunction
};
export default api
```

Actually exports the following

```
{ default: { get: someFunction } }
```

Need to support ES2015 module syntax.

**Comment by adrianhall** [comment]
Created the PR #332 for this - it's a one-liner change.  Need to discuss ES2015 unit tests though.

**Comment by danderson00** [comment]
ES2015 tests are going to be a little tricky. We will need to keep them separate in their own files and exclude the explicitly from runs on older versions or the parser will barf.
