### ISSUE TITLE
Custom API - Called Stored Procedure Example

### ISSUE THREAD

**Issue by egrimmius** [Azure/azure-mobile-apps-node#346]
Can you give a quick example of how to execute a stored procedure with parameters in a custom API?  I'm upgrading my app from Mobile Services.

**Comment by danderson00** [comment]
Here's a quick example:
```
mobileApp.api.add('test', {
    get: function (req, res, next) {
        var query = {
            sql: 'select @p1 as somevalue',
            parameters: [{ name: 'p1', value: 123 }]
        };

        req.azureMobile.data.execute(query).then(function (results) {
            res.json(results);
        });
    }
})
```

We'll use this issue as a placeholder to add a sample to the repository. Thanks!

**Comment by egrimmius** [comment]
Great!  Quick clarification - For a stored procedure, my query var would look like:

        var query = {
            sql: 'schema.storedProcedureName @parameterName',
            parameters: [{ name: 'parameterName', value: req.params.parameterValueName }]
        };

Thanks!

**Comment by adrianhall** [comment]
We'll also add it to the developer HOWTO doc on azure.com

**Comment by egrimmius** [comment]
I tweaked your example just a little to accommodate stored procedures and using invokeAPI in the MicrosoftAzureMobile iOS SDK.  This tested well in my mobile app.

mobileApp.api.add('test', {
    get: function (req, res, next) {
        var query = {
            sql: 'EXEC storeProcedureName @p1',
            parameters: [{ name: 'p1', value: req.query.parameterName }]
        };

        req.azureMobile.data.execute(query).then(function (results) {
            res.json(results);
        });
    }
})

Thanks again!  Sorry about the formatting.

**Comment by egrimmius** [comment]
How would I access different result sets in a stored procedure that returns multiple result sets?  As far as I can tell,

res.json(results);

only returns the first result set in the stored procedure.

Thanks.

**Comment by danderson00** [comment]
Setting query.multiple = true should return you an array of result sets. Let me know if this doesn't play the game!

**Comment by egrimmius** [comment]
It does!  Thank you!

**Comment by danderson00** [comment]
Created an issue to add some documentation for this. Thanks for the heads up!

**Comment by egrimmius** [comment]
In your documentation, can you also add an example for referring to the request's body?  I'm including the body, however req.body is undefined.  Any tips?  Thank you!

**Comment by adrianhall** [comment]
@egrimmius - you will need to add a body parser to get request.body set.

**Comment by egrimmius** [comment]
Would I do that on the app level or just in the custom api itself?

**Comment by adrianhall** [comment]
It's an express-level thing.  Something like:

```
var express = require('express'),
    bodyParser = require('body-parser');

var app = express();
app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ limit: '50mb', extended: true }));
```

We use this ourselves to provide support for images > 100Kb (which is the default upload size).  This is documented in the [Node.js server SDK HOWTO](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-node-backend-how-to-use-server-sdk/#TableOperations)

**Comment by egrimmius** [comment]
Great, that worked!  Thanks!

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/528596aa1eeb25eb2b2f49ff8c6125a8c820ce9a
