### ISSUE TITLE
Configure mount path in apiDefinition

### ISSUE THREAD

**Issue by thewizster** [Azure/azure-mobile-apps-node#350]
Currently I do not see a way to configure an express mount path in an apiDefinition.

**In Express we could use the following:**
```
// handler for the /user/:id path, which prints the user ID
app.get('/user/:id', function (req, res, next) {
  res.end(req.params.id);
});
```

In apiDefinition docs I see no way to configure the /user/:id path

Will this be added or is there another way to achieve this?

**Comment by danderson00** [comment]
I thought we had an issue for this, but I can't find it. The plan at this stage is to add a "route" property to an API definition to allow customizing of route parameters. Will keep this issue as a place holder.

Thanks!

**Comment by hakanostrom** [comment]
As a solution to the url-parameter I would suggest using
`var router = express.Router({mergeParams: true});`
in function _buildApiRouter()_ in src/express/api/index.js in the sourcecode. That way an endpoint can be added (in the main app.js) through
`mobileApp.api.add('myEndpoint/:id', apiDef);`
and then id property can be accessed inside apiDef´s functions through _req.params_

**Comment by danderson00** [comment]
Unfortunately, we won't be adding this feature, given how easy it is to mount express routers to achieve the same functionality and taking into account plans.
