### ISSUE TITLE
Add schemes and operationId for APIs exposed via Swagger

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-mobile-apps-node#351]
This is a required property for consuming swagger via PowerApps client.

**Comment by doodlemania2** [comment]
I can vouch for this need as well for .Net apps and the "Add Rest Client" functionality.

**Comment by danderson00** [comment]
We will also add the "schemes" property based on the protocol that was used to request the swagger json. Remember to use headers to determine if the request was SSL (secure socket is terminated at front end server, not worker).
