### ISSUE TITLE
Add bithound badge

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#353]
as well as keeping up to date with dependencies, we should be highlighting security concerns.   Bithound.io is free for open source projects and has slack integration - will scan the project on a build and determine if we have any security concerns.

**Comment by danderson00** [comment]
This looks useful. Interestingly, bitHound reports out of data dependencies where the dependency checker does not. We need to do a bit of configuration here, there are a bunch of legacy modules reported that we should ignore.
