### ISSUE TITLE
Argument of type 'MobileApp' is not assignable to parameter of type 'RegExp warning [TSD]

### ISSUE THREAD

**Issue by peterblazejewicz** [Azure/azure-mobile-apps-node#356]
Not directly related to NPM module, but to development files that are shipped with the module.
When I'm using VSCode with TypeScript definition files whenever instance of mobile app is passed as middleware to express application instance:
https://github.com/Azure/azure-mobile-apps-node/blob/master/samples/es2015/server/app.js#L36
```
app.use(mobile);    // Register the Azure Mobile Apps middleware
```
the compiler rises warning:
```
Argument of type 'MobileApp' is not assignable to parameter of type 'RegExp'. 
Property 'Exec' is missing in type MobileApp
```
It looks like MobileApp definition file does not provide interface request handler :unsure:

Thanks!

**Comment by georgeedwards** [comment]
It would be good to look at this, as the .d.ts file seems out of date? Another example is :

    table.access = 'authenticated';

which throws error: 

>[ts] Property 'access' does not exist on type 'Table'.
any

**Comment by danderson00** [comment]
Will have a quick look at this early next week, if it's a quick fix, we'll drop a release as well. Watch this space!

**Comment by danderson00** [comment]
I am struggling with this. My knowledge of TypeScript and definition files is somewhat lacking, particularly with the newer typings tool and how dependencies are declared. Can anyone give me some pointers / examples on how this issue should be properly resolved?

**Comment by georgeedwards** [comment]
Sure, using VSCode and the right click -> go to definition feature is really handy. I'll add a line note for how my issue could be resolved.

**Comment by danderson00** [comment]
I have submitted a PR to the DefinitelyTyped repo to address these issues. We have no intention to migrate to use the typings tool - TypeScript 2.0 will soon be released which introduces a new, better approach to managing dependencies and will provide a mechanism for including typings with npm modules that requires no additional installation aside from installing the azure-mobile-apps npm package.

If you would like to consume the typings before the DefinitelyTyped PR is merged, you can simply grab the [latest .d.ts file](https://github.com/Azure/azure-mobile-apps-node/blob/master/typings/azure-mobile-apps/azure-mobile-apps.d.ts) and drop it into your typings/azure-mobile-apps folder.
