### ISSUE TITLE
Node.js requires lower case ZUMO-API-VERSION query string

### ISSUE THREAD

**Issue by jsandersrocks** [Azure/azure-mobile-apps-node#357]
Repro.  Create a node backend and try to do a table operation using the query string:
See: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-client-and-server-versioning/
(Header works fine).

**Comment by danderson00** [comment]
@jsandersrocks I meant to jump on this sooner. This definitely works! It may be case sensitivity. Please try with a lower case query string.

**Comment by jsandersrocks** [comment]
it is case sensitivity.  Doc and code bug :-)  Error message and documentation all use upper-case

**Comment by danderson00** [comment]
Reopening as a placeholder to fix case sensitivity.

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/ae3fb083809627cb896108fd3c833aa6ec62f2cf
