### ISSUE TITLE
table.access = 'authenticated' only works at an operation level

### ISSUE THREAD

**Issue by ericmbarnard** [Azure/azure-mobile-apps-node#376]
Hi-
I've been working with this node library for a little over a month now, and as I was debugging some things this weekend using the latest version (2.0.1), I noticed my table endpoints weren't responding with 401's like I would expect. I have them setup like: 
```
var azureMobileApps = require('azure-mobile-apps');
var table = azureMobileApps.table();

// Turn on authentication
table.access = 'authenticated';

module.exports = table;
```

I pulled down your authentication [sample](https://github.com/Azure/azure-mobile-apps-node/tree/master/samples/authentication) to double check, and sure enough I saw the same thing there.

When I would hit: `http://localhost:3000/tables/todoitem`, at first it gives me: 
```
{
  "error": "An invalid API version was specified in the request, this request needs to specify a ZUMO-API-VERSION of 2.0.0."
}
```
But after I add the following header: `ZUMO-API-VERSION=2.0.0`, I get a `200 OK` response and an empty array `[]` (since the table hasn't been populated) - which is not what I was expecting. I did not have a `zumo-api-key` header in my requests, and I was fully expecting an auth error to comeback instead of `200`.

To clarify, I only found this when I was trying to mark a table as requiring authentication for every operation: 
```
table.access = 'authenticated';
```
However, I would think, for most, that is where you would start until you had a good reason to specify it for each operation.  In your [documentation](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-node-backend-how-to-use-server-sdk/#howto-tables-auth) it appears this should be a 'set it and forget it' type of thing. I'm a bit worried, though, that others might think it is working, but have not actually vetted it out. 

I did find that simply changing the property as [follows](https://github.com/Azure/azure-mobile-apps-node/blob/master/e2etest/tables/authenticated.js#L3-L4) works: 
```
//table.access = "authenticated"; 
table.authorize = true;
```

When I dig into the code a bit, I'm having trouble finding a quick bug/typo that might have caused this. I can see where I could add a unit test scenario to illustrate the issue, but after going through quite a bit of the codebase, I guess I first should ask what is the functionality supposed to be? `table.authorize = true` or `table.access = 'authenticated'` ? Once I know that, I'd be glad to try to contribute back some PRs to address the issue.

**Comment by adrianhall** [comment]
The relevant code is in src/configuration/importDefinition.js (around line 26 - setAccess() ) if you want to take a look.  Not sure why it isn't working via a quick look, but we'll do a longer look in the morning.

Q: Does authentication work as normal when the table does exist?  For example, if you call mobile.tables.initialize() with a static schema table (returns a Promise), then start listening?

**Comment by danderson00** [comment]
Good spot. 

This is because the `access` property was introduced mostly to simplify the implementation of EasyTables. It was only implemented for individual operations (e.g. read, update, etc.) and not as a default for the table. I didn't pick this up that our documentation shows it at a table level. 

Added to 2.0.2 milestone.

**Comment by ericmbarnard** [comment]
@adrianhall I can confirm that this is a problem with the static-schema sample you pointed to. This actually is pretty close to the setup that I have in my personal project, but I wanted to double check.
