### ISSUE TITLE
Either bundle queryjs or release separately

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#378]
There is a problem when git is not installed and you npm install azure-mobile-apps-node.  The error is 'git is not found'.

Consider either bundling queryjs as part of the prepublish or releasing queryjs as an npm module separately so that you can npm install azure-mobile-apps-node without git available.

**Comment by danderson00** [comment]
We have been intending to release queryjs as its own package for a while. This issue didn't occur to me! We'll release it shortly.

**Comment by danderson00** [comment]
query.js has been renamed to azure-query-js and lives at https://github.com/Azure/azure-query-js. The npm package with the name change lives in the `npm` branch so that existing azure-mobile-apps installations <= 2.0.2 don't break on reinstall.
