### ISSUE TITLE
Error: invalid column name 'version' - when performing a DELETE

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-node#382]
Just upgraded from version 2.0.0 to 2.0.1 and now I see an error every time I perform a delete.
Is this now a mandatory field on the table? I notice that the MSSQL statements/delete.js code accepts the version as a parameter, but I'm not sure where that's coming from.

**Comment by danderson00** [comment]
Yes, version is a required column. If you've manually created the table instead of using dynamic schema, you'll need to add the column. If not, let me know and I'll try to repro.

**Comment by joewood** [comment]
OK, is that just `version` and not `__version` (like the other reserved columns). Just checking the code, is the datatype `timestamp`?

**Comment by danderson00** [comment]
All reserved columns no longer have the __ prefix, i.e. they are now called createdAt, updatedAt, deleted and version. The column type is indeed timestamp (aka rowversion)

**Comment by joewood** [comment]
Is there a way to disable this version check? It seems to be an optional part of the context on the server side. Is this taken from the ETag? Background: - I'm reading through a different REST API and I don't really care about the version field - I just want to delete the record.

**Comment by joewood** [comment]
OK, I see that it's doing an HTTP OPTIONS then using the etag response to do the DELETE. Makes sense. Seems to work now I've added that column and removed the `__` on the other columns.
Thanks.
