### ISSUE TITLE
Reserved property test is case sensitive

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#384]
For example, sending an object with a `CreatedAt` property allows the `createdAt` reserved property to be updated. See https://github.com/Azure/azure-mobile-apps-node/blob/master/src/express/middleware/checkReservedProperties.js.

**Comment by ericmbarnard** [comment]
@danderson00 this brings up a good question. Is there a reason we need to throw errors on this instead of just ignoring the properties? It would make round-tripping the data between server and clients significantly easier if we didn't have to remember to chop off those properties before saving something. 

Something akin to: 
```javascript
if(propertyName){
    delete req.azureMobile.item[propertyName]; 
}
```

Or make it something we can configure by adding it to the defaults: 
```javascript
        data: {
            ignoreReservedProperties: true,
            provider: 'memory',
            schema: 'dbo',
            dynamicSchema: true
        }
```

**Comment by danderson00** [comment]
Good question. The client strips these properties, but we could potentially just ignore them to enable the same behavior when accessing the REST API directly. I'll discuss with colleagues.

**Comment by danderson00** [comment]
@ericmbarnard Reread your question. The logic for the reserved property test has moved from the data layer to a piece of express middleware. You can now successfully save items in table scripts without worrying about reserved properties, for example, retrieve a record in a table script (complete with reserved properties), modify it and save it.

The updatedAt is still updated to the latest time by a trigger, but other properties such as createdAt and deleted can be manipulated from table scripts, just not through the REST API.

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/9dd50797be39f3fe7053ce54254b44d91176aaf9.

Opened new issue for potentially ignoring reserved properties - https://github.com/Azure/azure-mobile-apps-node/issues/387
