### ISSUE TITLE
Error in log about sprintf

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#385]
Noticed this error in the logs when using verbose logging on Azure:

```
2016-03-20T04:16:29.873Z - �[35msilly�[39m: Executing SQL statement SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @table AND TABLE_SCHEMA = @schema with parameters [{"name":"table","value":"TodoItem"},{"name":"schema","value":"dbo"}]

sprintf() will be removed in the next major release, use the sprintf-js package instead.
```

**Comment by danderson00** [comment]
This is in a child dependency, we cannot remove this

**Comment by adrianhall** [comment]
Is it filed in the dependent module?  If not, we should file the issue there.

**Comment by danderson00** [comment]
I was actually thinking about reopening this as a reminder - it's likely they'll fix it soon if it's not already. I'll have to figure out which module is doing it and make sure it's up to date.

**Comment by danderson00** [comment]
This was caused by use of the sprintf function from the underscore.string package. This is an unnecessary dependency (the util.format builtin is an alternative to sprintf). Removed from azure-odata-sql-js.
