### ISSUE TITLE
Return 400 (bad request) when no fields are provided to update

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#386]
Currently, if you attempt to update an item without providing fields other than reserved properties, the error displayed is about incorrect SQL syntax. This should be more intuitive,

**Comment by mamaso** [comment]
feel like this may fit well in the wrapProvider assertions area so probably hold off until that's fleshed out

**Comment by danderson00** [comment]
Yep, good point, it could make things much easier

**Comment by danderson00** [comment]
Actually, was thinking about this and not sure I still agree - it's useful to be able to send a simple {} from postman.

**Comment by mamaso** [comment]
The issue says that you get a sql error - is that not the case?  Agree with simple postman

**Comment by danderson00** [comment]
Pretty sure... We might just be able to close this one. Give it a test, if it works, let's just close it.

**Comment by mamaso** [comment]
yep, no repro
