### ISSUE TITLE
Server-side queries and persistence layers

### ISSUE THREAD

**Issue by ericmbarnard** [Azure/azure-mobile-apps-node#389]
I'm very much in the thick of building a node-based back-end for our business, and I'm spending quite a bit of time with this framework. If I haven't said it - kudos on everything thus far!

I wanted to get an understanding of the bigger picture around persistence options, and thus server-side querying capabilities. Part of this is related to this [discussion on queryjs](https://github.com/Azure/queryjs/issues/16). I was wondering if we could get some clarity on the following points: 
1. [queryjs](https://github.com/Azure/queryjs), after digging through its code, appears to be very focused on the client-side aspect of querying. It provides a nice API for building up a query that eventually is translated into an OData-formatted querystring, so that an HTTP request can be made to an API for some data.  This is awesome for clients (apps, web pages, etc...) I feel, however, that this is very different from what we're wanting to do on the **server-side** when working with this Azure Mobile Apps framework. I've quickly found myself wanting to do JOINs, many-to-many relationship queries, and SELECT projections and queryjs doesn't support that. 
2. Raw SQL Queries are very much appreciated, but I look at them as more of a last option/fallback/bridge-until-something-better-arrives. We very much have plans to grow this server application, and I would like to have an abstraction that allows us to create dynamic queries a bit easier. (When I say dynamic, I mean dynamically adding WHERE and ORDER BY clauses based upon my user's roles, and parameters being passed in from the HTTP request itself). At the moment, I'm looking at pulling in some libs/ORMs (like [Sequelize](https://github.com/sequelize/sequelize)) that will give me these abstractions outside of queryjs, but I would like to stay in step with your plans if possible.
3. There appear to be a lot of plans/interest in supporting a variety of different persistence mechanisms: 
   #281, #290, #75, #73, #72, #71, #50
   
   In the .NET side of things, we have EF - which doesn't support all of those mechanisms, but it obviously does give us a VERY rich server-side querying capability, and it doesn't focus on client-side needs like queryjs appears to be. A node-based EF would be cool, but all I'm asking on this point is if there's some plans to have a strictly server-side abstraction layer for rich querying?

I was starting to look at making improvements to queryjs to support richer queries, but then realized it's used by the [JS Client](https://github.com/Azure/azure-mobile-apps-js-client/blob/e471b1a65701ca5339cf9718bee75d3d2e0a4f5e/package.json#L19) and the whole OData translation is quite important in that scenario.

**Comment by adrianhall** [comment]
Hi Eric - thanks for the input.  We are currently formulating the "what's next" plans.  When we can share our plans, I will certainly do so.   The only thing I can say right now is "stay tuned".

**Comment by danderson00** [comment]
It's worth giving some more detail on how queryjs is used. It's intended to be used on both client and server side - the output of the queryjs module is an OData query string. On the server side, modules in the azure-mobile-apps/src/query folder convert the OData string to SQL (the separation is due to legacy reasons).

It does support modifying the select statement - you can use the `select` function to specify a set of columns to select, but it doesn't support projections as such, i.e. you can only change the list of selected columns, not actually modify the result.

A reasonable short to medium term solution would be to implement a Sequelize data provider for azure-mobile-apps, and this is on our radar, but as Adrian mentions, we're currently formulating our roadmap.

**Comment by danderson00** [comment]
Thinking about projections, I suspect you can write SQL statements in the list of columns to select with the `select` function of queryjs. Pretty sure it just concatenates these onto the SQL query.

**Comment by ericmbarnard** [comment]
@adrianhall @danderson00 You guys are continuously very helpful - thanks for this. What you're describing with queryjs makes sense, and I see its purpose for being the transport mechanism for OData queries. I'll probably pull something like Sequelize or Squel into my project to handle the more complex querying scenarios that we need in our API endpoints.

**Comment by ericmbarnard** [comment]
"Staying Tuned" (for anyone else reading this): 
The OData/SQL tight coupling has been [moved](https://github.com/Azure/azure-odata-sql-js) and is being integrated in #391

**Comment by adrianhall** [comment]
Anything more to do on this?  I'm closing right now, but feel free to re-open if there is something else we are waiting on.
