### ISSUE TITLE
DynamicSchema not working if a new field is not initialized

### ISSUE THREAD

**Issue by m-andersen** [Azure/azure-mobile-apps-node#396]
While inserting a new row in SQL table, I had a few fields which where not yet initialized. They are set to null. They are to be initialized later. When executing table.insert(item) the insert fails because alter table has not been done:

`2016-04-01T15:00:12.486Z - debug: SQL statement failed - Invalid column name 'household_id'.: INSERT INTO [dbo].[MyfUserInfo] ([first_name],[last_name],[user_email],[household_id],[id],[user_id],[uniq_user_id]) VALUES (@first_name,@last_name,@user_email,@household_id,@id,@user_id,@uniq_user_id); SELECT * FROM [dbo].[MyfUserInfo] WHERE [id] = @id with parameters [{"name":"first_name","value":"Martin","type":{}},{"name":"last_name","value":"Andersen","type":{}},{"name":"user_email","value":"mega@test.com","type":{}},{"name":"household_id","value":null},{"name":"id","value":"847da140-03d2-4e55-867b-f4f896b67592","type":{"length":255}},{"name":"user_id","value":"1234","type":{}},{"name":"uniq_user_id","value":"my_id_1234","type":{}}]`

If I set it to some value the insert + ALTER table completes without errors.

**Comment by danderson00** [comment]
Hi @m-andersen, I'm not 100% clear on what you mean here. The insert failure is always logged, even if the dynamic schema operation completes afterwards, it doesn't necessarily mean a terminal failure.

Are you saying the alter table statement is not executed at all when some of the fields are null?

**Comment by m-andersen** [comment]
Hi
Yes, the alter table is not working when one of the new fields is set to null. It ends up trying to insert a few times it seems like. It is easy to reproduce. Only if the new field has a value, it works.

**Comment by danderson00** [comment]
Ahh, OK, I understand what you mean. This is because the type for the column cannot be determined - this is something that cannot be "fixed". You need to provide either data for the column on insert, or specify explicitly on the table definition, i.e.

    mobileApp.tables.add('tableName', { columns: { p1: 'string', p2: 'boolean' } }

or if you have your definition in a separate file:

    var table = require('azure-mobile-apps').table();
    table.columns = { p1: 'string', p2: 'boolean' };

Hope this helps!

**Comment by m-andersen** [comment]
Thanks for your input
