### ISSUE TITLE
"request.azureMobile.data.execute is not a function" when running completeall example

### ISSUE THREAD

**Issue by kNeerajPro** [Azure/azure-mobile-apps-node#400]
Hi 
Pardon me if I am missing something simple. I am mostly a mobile dev and trying to use Azure for the next project.
I have setup a mobile app service with a SQL server and a db on the portal.
Basically I am trying to run a local dev app service with local SQL server so I can test everything before pushing to the cloud.

**1st Question** - I have an API which basically runs a query using "request.azureMobile.data.execute". When I try to call this API using invokeAPI from iOS app pointing to server running on local host I get below error. I even get this error when I run "completeall" example as well.

**2nd Question** - I have been trying to find how to run the my DB server locally on Mac and connect it to the local running app service?

I think both issues are related. 

 request.azureMobile.data.execute is not a function
    at api.get (~/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/api/completeall.js:10:34)
    at Layer.handle [as handle_request] (~/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/layer.js:95:5)
    at next (~/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/Kneeraj/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Kneeraj/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Kneeraj/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (~/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/index.js:330:12)
    at next (~/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (~/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/index.js:176:3)
    at router (~/Downloads/azure-mobile-apps-node-master/samples/custom-api-sql-stmt/node_modules/express/lib/router/index.js:46:12)

**Comment by adrianhall** [comment]
1) Can you post your code, please.
2) It needs to be a Microsoft SQL Server, which doesn't run on Mac.  You can either use a SQL Azure database (adjust the firewall to allow the connection from your machine), or set up a VM running Windows and Microsoft SQL Server.

I will leave this open for right now, pending your code.

**Comment by kNeerajPro** [comment]
Hey thanks a lot of your replying. I really appreciate the support you have given.
1) Code is hardly changed from the git clone of app service from Azure. Posting the contents here for app.js and EasyAPI. Also, I am just wondering how my local app service node.js server is connecting to db server in the cloud? Where is this connection to db code ?

2) I don't want to connect to my production db on the cloud. I want to replicate it and run it locally so that I have app service node.js server and db server both running on my mac locally. I will play with it for development purpose and then push things to the production/Azure cloud. 
**
Comments regarding your solution for running db on mac**
1) With your first solution on mac I will connect to the production db on the cloud which I don't want to. I think I can to replicate the production Db and create another dev db and host it on the same db server on Azure cloud? How do I connect my local app service node.js server to this dev db on the cloud? 
2) I don't want to prefer running VM on my mac as it will be too heavy to use while I am doing development. 

I am really stuck on this and your help will be appreciated!!

**app.js**
// ----------------------------------------------------------------------------
// Copyright (c) 2015 Microsoft Corporation. All rights reserved.
// ----------------------------------------------------------------------------

// This is a base-level Azure Mobile App SDK.
var express = require('express'),
    azureMobileApps = require('azure-mobile-apps');

// Set up a standard Express app
var app = express();

// If you are producing a combined Web + Mobile app, then you should handle
// anything like logging, registering middleware, etc. here

// Configuration of the Azure Mobile Apps can be done via an object, the
// environment or an auxiliary file.  For more information, see
// http://azure.github.io/azure-mobile-apps-node/global.html#configuration
var mobileApp = azureMobileApps({
    // Explicitly enable the Azure Mobile Apps home page
    homePage: true,
    // Explicitly enable swagger support. UI support is enabled by
    // installing the swagger-ui npm module.
    swagger: true
});

// Import the files from the tables directory to configure the /tables endpoint
mobileApp.tables.import('./tables');

// Import the files from the api directory to configure the /api endpoint
mobileApp.api.import('./api');

// Initialize the database before listening for incoming requests
// The tables.initialize() method does the initialization asynchronously
// and returns a Promise.
mobileApp.tables.initialize()
    .then(function () {
        app.use(mobileApp);    // Register the Azure Mobile Apps middleware
        app.listen(process.env.PORT || 3000);   // Listen for requests
    });

**EasyAPI**
var api = {
    get: (request, response, next) => {
       // response.send(200, {"text":"Hello todo api"});
    var query = {
            sql: 'UPDATE TodoItem SET text=@text WHERE taskid=@taskid',
            parameters: [
                { name: 'text', value: request.query.text},
                //{name: 'id', value: '0550CBE6-623A-4AD2-A949-618F2AF00C98'}
                {name: 'taskid', value:'9FD2700E-5A9D-4243-9D0B-4CC64C1A9EA3'}
            ]
        };

        request.azureMobile.data.execute(query)
        .then(function (results) {
            //response.json(results);
             response.send(200, {"text":"Hello api"});
        }); 
    }
};

module.exports = api;

**Comment by danderson00** [comment]
Hi @kNeerajPro,

This is likely due to use of the "memory" data provider - this provider is configured if you do not specify a configuration for mssql. The memory provider does not support direct SQL queries. For now, you need to configure a MSSQL database.

In the next week or two, we will be releasing a SQLite data provider that will enable you to do local development without needing a MSSQL database.

Hope this helps!

**Comment by adrianhall** [comment]
Hey @kNeerajPro 

I posted a blog post here: https://shellmonger.com/2016/04/01/30-days-of-zumo-v2-azure-mobile-apps-day-2-local-development/ 

This covers how to connect your local development environment to a database in the cloud.  It does not cover cloning your database - a quick google search produced this: http://blog.idera.com/sql-server/how-to-make-a-copy-of-a-database-on-windows-azure-sql-database/ - I have not tried this process myself however.

**Comment by kNeerajPro** [comment]
Hey Adrian, Anderson 
Thanks a lot for the reply. 
As I see, I have 2 options -
1) Create a copy of database on Azure and call it dev database and connect my local app service to it? Does Azure charges etc  for another db on same server?
2) As per Anderson above, I can MSSQL server locally and connect it to my local app service. Any help if I want to do this? 
Thanks

**Comment by adrianhall** [comment]
1) Yes, Azure charges on a per-database basis.  You can change the dev database to a cheaper plan, however, since you don't need production performance.
2) You are using a Mac.  You can't run MS-SQL on a Mac - see here for a list of systems MS-SQL supports: https://www.microsoft.com/en-us/download/details.aspx?id=42299

**Comment by kNeerajPro** [comment]
@danderson00 I am not sure what you mean by memory driver? I have just done git clone <app-service> and run node server locally. I have not done any kind of database setting. I was hoping that app service code connects to the remote db server by default and probably I can change it to a db server locally.  Could you please explain it a bit?

**Comment by danderson00** [comment]
azure-mobile-apps uses "pluggable" data providers, i.e. providers can be created for different data sources, e.g. SQLite, Mongodb, etc. If you do not specify a data configuration, it will use the memory data provider - the memory data provider is quite limited in functionality.

If you are using an Azure SQL database, you'll need to configure the database. When your app is deployed to Azure, you do this through the "Data Connections" section of the portal. Locally, we recommend that you create a file called `azureMobile.js` (make sure you exclude this from git deployments by adding the file name to your .gitignore file) and putting the following code in the file:

```javascript
module.exports = {
  data: {
    server: 'servername.database.windows.net',
    database: 'databasename',
    user: 'username',
    password: 'password'
  }
}
```

As mentioned, we'll be release a SQLite data provider in the next couple of weeks that will become the default and this will all work out of the box.

**Comment by kNeerajPro** [comment]
Great I understood a lot from this discussion. 
Thanks a ton @adrianhall @danderson00  I really really  appreciate you guys clearing so many doubts!! 
Kudos to you guys!!
