### ISSUE TITLE
sqlite provider internal serializer not used correctly - transaction in progress errors for parallel statements

### ISSUE THREAD

**Issue by chris-armstrong** [Azure/azure-mobile-apps-node#417]
At the moment, the `src/data/sqlite/serialize.js` module is used to ensure that statements sent to the sqlite connection are executed serially (which seems to be needed because each statement is wrapped in BEGIN TRANSACTION and COMMIT statements). This module returns a function that maintains an internal queue of statements to be executed on the connection.

The problem is that the codebase currently seems to create a new version of this function at various points in the code, which in turns create multiple unrelated queues for the same connection e.g. in `dynamicSchema.js`:

```javascript
var serializeModule = require('./serialize'),
//...
module.exports = function (connection, table) {
    var serialize = serializeModule(connection),
        schema = schemaModule(connection);
```

This means that if you execute two queries in parallel (e.g. in a Promise.all() wrapper) such as:

```javascript
Promise.all([
  context.data('MyTable').insert({ name: 'test'}), 
  context.data('MyOtherTable').insert({flag: true})
]).then(function(results) {
 ...
});
```

the sqlite provider will try and run the statements in parallel instead of serially, resulting in errors like this:

```
Error: SQLITE_ERROR: cannot start a transaction within a transaction] errno: 1, code: 'SQLITE_ERROR'
```

If you add tracing to the statement start / finish in `serialize.js`, you can see it beginning two statements at the same time. The correct solution would be to save the serialize function created in `src/data/sqlite/index.js` on the connection, and utilize that from `src/data/sqlite/dynamicSchema.js`, `src/data/sqlite/columns/index.js`, etc.

**Comment by danderson00** [comment]
Good spot, you are totally right. I don't know how this slipped through, I spent a fair bit of time getting this right. We'll get this fixed ASAP.

**Comment by danderson00** [comment]
@chris-armstrong Thanks for the report! Referenced PR should resolve. Included integration test fails on master branch, fixed in the PR.
