### ISSUE TITLE
Add File Sync support to Node server SDK

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-node#421]
Should follow the pattern here: https://github.com/Azure/azure-mobile-apps-net-files-server

Tutorial: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-blob-storage/

**Comment by danderson00** [comment]
This is a duplicate of https://github.com/Azure/azure-mobile-apps-node/issues/67, but provides a bit more info. Closing the other issue. Will have a chat with you about priority.

**Comment by lindydonna** [comment]
@danderson00 You should chat with @adrianhall about priority, since I don't know what other work there is.

**Comment by danderson00** [comment]
This is implemented in the Azure/azure-mobile-apps-node-files repo with automatic loading of the plugin implemented in this repo.
