### ISSUE TITLE
I cannot upgrade mobile services database to mobile apps

### ISSUE THREAD

**Issue by educosta** [Azure/azure-mobile-apps-node#428]
Hi,

I have a mobile services and I want upgrade (not migrate) to mobile apps, but I this not works because the old tables has __columns.

This is right? What is the alternative? This datebase is my production db.

Thank you!

**Comment by danderson00** [comment]
Check out https://raw.githubusercontent.com/Azure/azure-mobile-apps-node-compatibility/master/static/createViews.sql. This SQL script will create you a view in the dbo schema that should work seamlessly with Mobile Apps. Keep in mind that if you didn't have soft delete enabled in Mobile Services (i.e. have a __deleted column in each table), this script will create the column in the source database. It's probably a good idea to work with a backup of your production database until you're ready to go live.

**Comment by educosta** [comment]
Hi,

Thank you for your response.

But the insert and update operations, how it works?

Regards,
Eduardo

**Comment by danderson00** [comment]
I'm not sure what you're asking. You'll also need to update your client to use the latest version - this version will use system columns without the __ prefix and will work against the views created by the above script. Otherwise, insert and update should work the same.

**Comment by educosta** [comment]
If I connect my current database with __ columns mobile apps crash because it try create other version column and sql return a error "table can have only one timestamp column.

This is database is for mobile services and other applications, I can't create new columns or remove columns from tables.

**Comment by danderson00** [comment]
This is because the mobile app server looks for a column called "version" and creates it if it doesn't exist. If you run the above SQL script, it creates database views that map the __ columns, e.g. "__version" becomes simply "version". 

You need to take the following steps:
- Run the SQL script linked above against your database
- Upgrade your client app to use the latest version of the Mobile Apps library
- Point your mobile app server at the database

Once you have done these three steps, it should work.

Does this make sense?

**Comment by educosta** [comment]
Sure, but if I'm going to use views to map "__column" to "column", its going to work for queries, but what about when I need to insert data using mobile apps?

**Comment by danderson00** [comment]
Ahh, I see what you are asking. Inserts and updates work fine with the created views.

**Comment by educosta** [comment]
Good! Thanks you!

**Comment by mikejohanson** [comment]
When try to do an update utilizing the Mobile Apps Client Javascript SDK, the server is giving me:
```
2016-07-16T05:57:21.492Z - error:  RequestError: Cannot update a timestamp column.
    at C:\Azure\GESDATE%20Mobile%20App\node_modules\azure-mobile-apps\node_modules\mssql\lib\tedious.js:739:17
    at Connection.emit (events.js:107:17)
    at Parser.<anonymous> (C:\Azure\GESDATE%20Mobile%20App\node_modules\azure-mobile-apps\node_modules\mssql\node_modules\tedious\lib\connection.js:204:16)
    at Parser.emit (events.js:107:17)
    at Parser.<anonymous> (C:\Azure\GESDATE%20Mobile%20App\node_modules\azure-mobile-apps\node_modules\mssql\node_modules\tedious\lib\token\token-stream-parser.js:42:15)
    at Parser.emit (events.js:107:17)
    at readableAddChunk (C:\Azure\GESDATE%20Mobile%20App\node_modules\azure-mobile-apps\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:210:18)
    at Parser.Readable.push (C:\Azure\GESDATE%20Mobile%20App\node_modules\azure-mobile-apps\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:169:10)
    at Parser.Transform.push (C:\Azure\GESDATE%20Mobile%20App\node_modules\azure-mobile-apps\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at doneParsing (C:\Azure\GESDATE%20Mobile%20App\node_modules\azure-mobile-apps\node_modules\mssql\node_modules\tedious\lib\token\stream-parser.js:87:17)
```

I have followed the instructions above, have I missed something?

**Comment by danderson00** [comment]
Hi @mikejohanson can you provide a little more detail? 

The columns with the underscore prefix are used by the older Mobile Services product. Equivalent columns without the prefix are used by the newer Mobile Apps. You need to use compatible versions of the client and server, i.e. you must use the Mobile Services client with the Mobile Services backend, and same for Mobile Apps.

If you've used the SQL view to upgrade the database schema to that required by Mobile Apps, and are now using the Mobile Apps backend, you also need to use the Mobile Apps client.

**Comment by mikejohanson** [comment]
Hi @danderson00,

Yes, I am using the new mobile apps running locally on my machine. I also am running https://github.com/Azure/azure-mobile-apps-js-client on the client side. When I make a an update call 

`client.getTable("mytable").update(item);`

the server throws the RequestError above, that it cannot update a timestamp column. I have a view for every table in the database that maps to the new non underscore prefixed system columns generated by the SQL script from your earlier post.

**Comment by danderson00** [comment]
Are you sure the client is sending a column called __version? With Mobile Apps, it should be called simply "version".

**Comment by mikejohanson** [comment]
Yes, I can see it being retrieved in the GET with the underscore prefixed properties.

**Comment by danderson00** [comment]
Are you using Mobile Services or Mobile Apps backend? This looks like Mobile Services.

**Comment by mikejohanson** [comment]
:) I hear what you are saying...it used to be Mobile Services, so the db structure still reflects that. I ran the script to create the views the map the old system properties to the new ones. However, it is Mobile Apps that I am running. Correct me if I'm wrong, but you can't run Mobile Services locally if that helps prove its Mobile Apps that I'm running.

**Comment by danderson00** [comment]
It looks like Mobile Apps is not using the right database schema name. The script that creates the database views creates them in the `dbo` schema - the SDK uses this schema name by default, but it can be configured to use a different schema name - did you configure a different schema name?

**Comment by mikejohanson** [comment]
Yes, I did configure it to use a different schema name to match what it was in Mobile Services.

**Comment by danderson00** [comment]
That's it - the SQL statements will be constructed using the dbo schema - the views then map through to the Mobile Service schema name. Let us know how it goes!

**Comment by mikejohanson** [comment]
Ok awesome, looks like its working! Thank you!
