### ISSUE TITLE
Push using templates does not work

### ISSUE THREAD

**Issue by m-andersen** [Azure/azure-mobile-apps-node#433]
I have begun working on getting push from the backend to android app working. The basic example is working where I use gcm format

var push_payload = {
        "data": {
            "message": "lalala"
        }
    };
    
    if (context.push) {
        // Send a GCM native notification.        
        context.push.gcm.send(userTag, push_payload, function (error) {
            if (error) {
                console.log('Error while sending push notification: ', error);
            } else {
                console.log('Push notification sent successfully!');
            }
        });
      
However, this is not desireable as I would like to send one push msg and service bus finds out what platform it is. That is where templates should be useful, but it doesn't work.

This doesn't work
var push_payload2 = '{"messageParam": "This is a template payload."}';

    if (context.push) {
        // Send a GCM native notification.        
        context.push.send(userTag, push_payload2, function (error) {
            if (error) {
                console.log('Error while sending push notification: ', error);
            } else {
                console.log('Push notification sent successfully!');
            }
        });

Please check if there is a bug.
Also, it would be nice with example of this in the node.js Azure mobile apps package as I think this is what most people would want to use.

**Comment by adrianhall** [comment]
Your template is wrong.  Your push_payload2 should follow the same format:

```
var push_payload = {
    data: {
        messageParam: "This is a template payload"
    }
}
```

There is an ever growing set of samples - including with templated/tagged push notifications - in the samples directory.

**Comment by m-andersen** [comment]
I forgot to highlight that according to MS documentation, I should be able to send a generic payload for both iOS, android, windows using context.push.send() rather than the platform specific function context.push.gcm.send(). If I use context.push.send() I don't receive any push message. I unerstood that notification service knows what platform a user is using and then formatting it correctly. Or is this not how it works? I would like to avoid having both context.push.gcm.send(), context.push.apn.send(), context.push.wns.send() in my code. Is that possible?
