### ISSUE TITLE
"NotBeforeError" from Server using version 2.1.7

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-node#438]
After upgrading to version 2.1.7 I'm seeing a lot of "NotBeforeError" when authenticating using a service provider JWT (Google or Facebook), then after receiving a Zumo token back but then going on to use that zumo token in an API call. Does the new version have a stricter set of rules for clock synchronization?

**Comment by danderson00** [comment]
Hi @joewood we didn't make any changes in that area, this one sounds really strange. It's a little hard to tell if it is a change in token validation or how they are generated. I would guess the latter, but I'll do some investigation and get back to you.

**Comment by danderson00** [comment]
One question - how are your tokens generated? Are you using an identity provider like google or facebook, or are you using custom authentication?

**Comment by joewood** [comment]
Hi Dale, yes this an auth token from Facebook, exchanged for a zumo token using the `.auth/login/facebook` url. That same token returns a validation error when performing other requests to the same service.

**Comment by joewood** [comment]
It looks suspiciously related to this: https://github.com/auth0/node-jsonwebtoken/issues/152
Where the check was failing on equal times of creation of the token (rounded down to the nearest second).

**Comment by cgillum** [comment]
Hi @joewood, would it be possible to provide the exact text of the NotBeforeError you're seeing (and where you are seeing it)? Up to 5 minutes of clock skew should be allowed.

**Comment by danderson00** [comment]
I suspect @joewood is right - the node jsonwebtoken package does not implement the not before check to spec - if the values are equal, it fails validation (incorrectly). Try upgrading to jsonwebtoken 7.0.0 by changing the package.json file and see if that resolves the issue. I will update the dependency version on our side and release a new version.

A question that is on my mind - are you using App Service Authentication (i.e. have turned authentication / authorization on through the portal)? If so, the azure-mobile-apps library shouldn't revalidate the token as the token will already be validated by App Service Auth.

**Comment by joewood** [comment]
Yes, App Service Authentication is on. So the container should be authenticating. But doesn't the node app also check the token too through the express middleware? I tried putting a 2 second delay in the login sequence and that seemed to fix it. I'll try to upgrade too.

**Comment by danderson00** [comment]
I can't repro locally, @joewood I checked in an updated package.json, can you verify it resolves the issue before I publish it to npm? Cheers!

Good spot on the jsonwebtoken github issue!

Should be resolved by https://github.com/Azure/azure-mobile-apps-node/commit/92c18e42cd524b19b7fff70cc09e548446fa74ce

**Comment by joewood** [comment]
I just npm installed from GitHub and it seems to have fixed the issue. I removed the delay and the login sequence works. It was a little intermittent (I guess because sometimes it was lucky crossing the second boundary). Seems OK so far.
