### ISSUE TITLE
WP8.1 Silverlight Support

### ISSUE THREAD

**Issue by jieverson** [Azure/azure-mobile-apps-node#439]
I have an WP8.1 Silverlight App that I'm keeping support, and I would like to migrate to the new Azure App Service. I could not find an API (all the Nugget API seens to be for Universal Apps or Xamarin).
Will I have to use REST API or do you guys have any unreleased code for this?

**Comment by adrianhall** [comment]
Hi @jieverson - the right repo is https://github.com/azure/azure-mobile-apps-net-client - this is purely for the node implementation.  You'll find the right people hanging out there.  Unfortunately, we can't move questions between repositories, so you will need to re-post.
