### ISSUE TITLE
Example authstub doesn't seem to work with a provider token POST on /.auth/login/<provider>

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-node#441]
This may be a configuration problem on my end, but the `authstub.js` example file for debugging locally seems to post an HTML response to `/.auth/login/<provider>`, where the SDKs seem to be expecting JSON.

https://github.com/Azure/azure-mobile-apps-node/blob/d02419801e9faf2dde20150f0a856f22e40aab4b/src/express/middleware/authStub.js#L31

Is this expected, or should the body be ignored in favor of the querystring on the redirect?

**Comment by danderson00** [comment]
Not clear on the behavior you're experiencing here. The line you reference is returning the HTML page that redirects to the /.auth/login/done endpoint. This makes the client redirect with a precanned token to the done endpoint, signalling the authentication process is complete. The client sees the redirect and picks the token up out of the querystring.

Are you maybe referring to the case where you already have a provider token and you're logging in wiht this on the client? (i.e. authenticating with a client flow)

**Comment by joewood** [comment]
Hi Dale, yes - I'm posting a provider token. I had to change the code to reply back with the zumo token. It confused me a bit because the older code seemed to support that interaction.

**Comment by danderson00** [comment]
What's the behavior you're experiencing? Does it still authenticate and return a token but returns the pre-canned token (i.e. user id of sid:00000000000000000000000000000000) instead of the provider token? It should be fairly simple to extract the provider token from the request.

**Comment by joewood** [comment]
No, I see a JSON parse error on the returned HTML. I changed the code to just post the JSON with the zumo token and it's fine. It'll just be nice to have a generic authstub that handles both interactive and provider based login routes.

**Comment by danderson00** [comment]
Which platform are you using for the client? The authentication brokers are slightly different for each platform.

**Comment by joewood** [comment]
This is the JS API client in a Single Page App, where the provider login (facebook) is handled separately (via a React based component).

**Comment by danderson00** [comment]
Hey @joewood, I made a small change that I think will resolve this issue. Basically maintain the old behavior on /.auth/login/provider if the request method is GET, otherwise return a token if the request method is POST. You can see the change at https://github.com/danderson00/azure-mobile-apps-node/blob/authStubFix2/src/express/middleware/authStub.js#L23 and can consume the update by executing `npm install danderson00/azure-mobile-apps-node#authStubFix2`.

I'm guessing you've got this stuff already set up. Any chance you could give it a quick test?

**Comment by danderson00** [comment]
Should be resolved by https://github.com/danderson00/azure-mobile-apps-node/commit/f18a5194ac95acd7b767ab4f5722ad6b880206d6
