### ISSUE TITLE
Signing keys are no longer hex decoded unless easyauth is specified

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#444]
EasyAuth hex encodes signing keys before setting the WEBSITE_AUTH_SIGNING_KEY environment variable. https://github.com/Azure/azure-mobile-apps-node/commit/580c79ae74ce5d3838b6d6d1f1d1c31f758ab1a4 introduced a change where signing keys are only hex decoded if the easyauth option is also specified (The easyauth option is automatically set when hosted and EasyAuth is enabled).

As a workaround, manually specifying the easyauth option should work, but this is not intuitive.

```Javascript
module.exports = {
    auth: {
        secret: 'WEBSITE_SIGNING_KEY value from hosted site',
        easyauth: true
    }
};
```

**Comment by georgeedwards** [comment]
NB: This workaround doesn't really work with typescript (unless you ignore issues), as `azure-mobile-apps.d.ts` line 116, doesn't contain a definition for `easyauth` in it's auth interface.
