### ISSUE TITLE
Update gh_pages for release

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#452]

**Comment by danderson00** [comment]
http://azure.github.io/azure-mobile-apps-node/global.html#sqliteDataConfiguration

and

http://azure.github.io/azure-mobile-apps-node/module-azure-mobile-apps_configuration_Data%2520Providers.html

Any suggestions for improvement, e.g. make it easier to find?

**Comment by danderson00** [comment]
Suggestions from Adrian by email:

In the dataConfiguration section: http://azure.github.io/azure-mobile-apps-node/global.html#dataConfiguration

1)	Provide a bulleted list of providers and the links to the provider notes
2)	Remove memory as a provider
