### ISSUE TITLE
Error: Cannot find module 'bcrypt'

### ISSUE THREAD

**Issue by edwinlxl** [Azure/azure-mobile-apps-node#453]
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'bcrypt'

the custom authentication sample didn't work when the following line of code is present at login.js,
bcrypt = require('bcrypt');
and I cann't install bcrypt using the command "npm install -g bcrypt"

**Comment by danderson00** [comment]
Did you run `npm install` from the sample folder? You can see in the package.json file (https://github.com/Azure/azure-mobile-apps-node/blob/master/samples/custom-authentication/package.json#L10) that the bcrypt module is listed as a dependency. The module that is installed should be https://www.npmjs.com/package/bcrypt.

**Comment by danderson00** [comment]
Hi @edwinlxl, did this resolve your issue?

**Comment by edwinlxl** [comment]
I run the command "npm install bcrypt" from D:\home\site\wwwroot, but it gives me the following error:
I use another library, bcrypt-nodejs, now it generates valid token and the sample works


npm WARN prefer global node-gyp@3.4.0 should be installed with -g
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\npm\3.5.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\4.2.3\\node.exe" "c:\\Program Files (x86)\\npm\\3.5.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\home\site\wwwroot\node_modules\bcrypt
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.2.3\\node.exe" "D:\\Program Files (x86)\\npm\\3.5.1\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\wwwroot\npm-debug.log

**Comment by adrianhall** [comment]
Glad it works for you.

**Comment by danderson00** [comment]
Hi @edwinlxl, there is actually a problem with npm packages that require native (binary) modules. bcrypt is one of those. The workaround is to install the package on your local machine (with the same version of node) and include the node_modules/bcrypt folder in your deployment package.

https://social.msdn.microsoft.com/Forums/en-US/ee89c887-32ef-4b11-a85e-b8a4e4c3addb/nodejsweb-apps-issue-during-deployment-to-azure-fatal-error-c1902-program-database-manager?forum=opensourcedevwithazure
