### ISSUE TITLE
Total count includes all rows in the table (including deleted records) when count is requested

### ISSUE THREAD

**Issue by Anshdesire** [Azure/azure-mobile-apps-node#454]
Added includeTotalCount() in query so it is returning count including **soft deleted data** in that case not able to create pagination with right data same issue is with search parameters , i need only count matching in query, or without search all non-deleted data count how to solve that ?

**Comment by danderson00** [comment]
@Anshdesire thanks for reporting this. I have reproduced the issue where the total count includes deleted records (and likely other filters that should be applied but are not).

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/37ddc0e0d27db07907e82c6315ba841f23346165

**Comment by Anshdesire** [comment]
Thanks for quick response.
