### ISSUE TITLE
No way to perform like queries using query-js object

### ISSUE THREAD

**Issue by Anshdesire** [Azure/azure-mobile-apps-node#458]
No way to perform like queries.

**Comment by danderson00** [comment]
To clarify - OData has an equivalent, the substringof function, and our OData -> SQL formatter (https://github.com/Azure/azure-odata-sql-js) supports this, but the query API (https://github.com/Azure/azure-query-js) exposes no way to generate such an OData statement.

**Comment by danderson00** [comment]
Added https://github.com/Azure/azure-query-js/issues/17

**Comment by Anshdesire** [comment]
Exactly i have checked with that and sometimes it's little difficult to play with only custom queries in my case i have pagination search and many more is needed so addition of this feature will be very good.

**Comment by danderson00** [comment]
Issue tracked in azure-query-js repository, closing here
