### ISSUE TITLE
Multiple fields in where query is not available.

### ISSUE THREAD

**Issue by Anshdesire** [Azure/azure-mobile-apps-node#459]
Multiple fields in where query is not available.

**Comment by danderson00** [comment]
Hi @Anshdesire, if I understand correctly, this may do what you need:

```
var categoryIds = [1, 4, 5];
return context.tables('items').where(function (ids) {
  return this.categoryId in ids;
}, categoryIds).read();
```

**Comment by Anshdesire** [comment]
@danderson00  - We have already discussed this on gitter right. Example you have given is good for IN but what if i want to search with two fields (can assume composite key related data ) or you can assume use of OR , NOT.

**Comment by danderson00** [comment]
Ahh, sorry, I misunderstood on gitter, too. Gotcha. How about:

```
return context.tables('items').where(function () {
  return (this.genre === 'rock' || this.genre === 'classical') && this.category === 'sale';
}).read();
```

query-js parses Javascript using esprima and creates a custom expression tree from it. Quite a bit of functionality is supported. I thought the tests were a decent reference, but not really. Those two examples give you good context how to use it. Have a play and let me know if this answers your question.

**Comment by Anshdesire** [comment]
Oh yes I have already tried this. But it reduces performance :(

**Comment by danderson00** [comment]
@Anshdesire What do you mean reduces performance? Queries with standard operators like ==, +, -, &&, ||, etc should generate reasonably efficient SQL. You can see the SQL by running the app with the `---logging.level silly` command line parameter.

Can you give us an example of where the query is less efficient than you expect?

**Comment by danderson00** [comment]
Closing this issue as I'm pretty sure we support what you require. Please feel free to reopen with an example if you find a scenario that doesn't work, or performs poorly (aside from those we know about, like using the in operator)
