### ISSUE TITLE
Add user parameter to table data access factory function

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#461]
Calling context.tables('name').read() does not restrict records to current user, even if the table is marked as per user. Adding a parameter to the factory function should make this easier for users:

     context.tables('name', context.user).read()

**Comment by danderson00** [comment]
@fabiocav @paulbatum @brettsam 

Paul raised a concern that the per user filters are only applied for incoming read queries, i.e. adds query filters in middleware - queries that are executed directly from table operations on the server are not automatically filtered. This is important to be able to do this (i.e. user filter should not be automatically applied), but it's kind of easy for users to shoot themselves in the foot.

My initial proposal was to add a user parameter to the server side data access API that has the same effect. Do you think this is good enough?

**Comment by danderson00** [comment]
After a discussion with Paul, we agree that a parameter should be on the factory function for the table data access object (as opposed to each individual table operation, read, insert, update, delete). This parameter can also indicate NOT to check for a user (e.g. by passing null). We will also throw an exception if this parameter is not provided when the table is a per user table - this forces the developer to make an explicit decision.

**Comment by danderson00** [comment]
An example:

    context.tables('todoitem', context.user).read()

will filter all read records to the current user

    context.tables('todoitem', null).read()

will read all records

    context.tables('todoitem').read()

will throw an exception IF the table is a per user table

**Comment by paulbatum** [comment]
Yep I feel like this maximizes the chances of the developer getting it right. Does the extra parameter justify switching to the options pattern? Maybe:

    context.tables('todoitem', { authorizationFilter: context.user }).read()

and

    context.tables('todoitem', { authorizationFilter: 'all_users' }).read()

Passing null as the authorization filter would certainly work too. Just thinking about how to make code that uses this API more readable...

**Comment by danderson00** [comment]
Yeh, not making such a decision now is one of those things that Murphy has declared will bite us down the track. Agreed.

**Comment by danderson00** [comment]
@pbatum @fabiocav @adrianhall What do you think of the following API:

```Javascript
// This will not apply per user permissions and will return all records
table.read(function (context) {
    var otherTable = context.tables('otherTable', { perUser: false })
    otherTable.read().then(function (results) {
        /* ... */
    })
})

// This WILL apply per user permissions and will only update the record in
// the 'otherTable' if it is "owned" by the current user
table.update(function (context) {
    var otherTable = context.tables('otherTable')    
    otherTable.update({ id: context.item.otherId, value: context.item.otherValue }).then(function (results) {
        /* ... */
    })
})

// We could also add a per request option that applies to all tables involved in the request
table.read(function (context) {
    context.perUser = false
    var otherTable = context.tables('otherTable')    
    otherTable.read().then(function (results) {
        /* ... */
    })
})

// Or even a global default that is set in global configuration, something like
var mobileApp = require('azure-mobile-apps')({ enforcePerUserInScripts: false })
```

**Comment by danderson00** [comment]
@paulbatum Got your username wrong

**Comment by paulbatum** [comment]
I think I'm fine with the move to implicit filtering by default. We might need some extra logging statements to help people debug what the hell is going on when they are invoking an operation anonymously and that operation is reading another table that has perUser:true. 

I have a slight preference for more generic terminology than "perUser", but I agree that "useAuthorizationFilter" is wordy and its meaning is less obvious (especially while the only filtering rule we have is per user). So I'm not sure if I have a better suggestion.

**Comment by danderson00** [comment]
Agreed on the first point, will add some silly level logging when filters are applied.

On the second, I feel like it's trying to anticipate the design of features that we haven't designed yet. However, I do agree that we will probably end up with an equivalent of parse's useMasterKey. Given that the term "perUser" exists elsewhere in the API surface and probably always will, I am comfortable with using it here.

**Comment by danderson00** [comment]
OK, after a bit more thinking, I do agree. One small thing is that inserts also attach the user id property, so strictly speaking, it's not just a filter. Just to make the naming harder haha

**Comment by fabiocav** [comment]
I like the proposed API and agree with the points that have been made about logging and naming (particularly about using a more generic terminology), but I'm, unfortunately, in the same boat and don't have any good suggestions right now.

**Comment by danderson00** [comment]
This is superseded by https://github.com/Azure/azure-mobile-apps-node/pull/469
