### ISSUE TITLE
getIdentity Doesn't Parse Schemas.Microsoft.Com claims

### ISSUE THREAD

**Issue by madgrizzle** [Azure/azure-mobile-apps-node#463]
*Caveat: I know very little about what I'm talking about so the terminology I use may be completely wrong*
When you run user.getIdentity and try to get a claim that's based on schemas.microsoft.com, such as objectidentifier and tenantid, it responds back with 'undefined'.

I found in normalizeClaims.js that there's a statement to parse schemas.xmlsoap.org/ws claims so I copied it and changed the parameter to schemas.microsoft.com and it worked (can now get objectidentifier and tenantid).

This is the line I added:

` if (claim.typ.indexOf('http://schemas.microsoft.com') !== -1)
            setClaim(target, claim.typ.slice(claim.typ.lastIndexOf('/') + 1), claim.val);`

**Comment by danderson00** [comment]
This looks reasonable, I'll do some verification and get this added soon.

**Comment by adrianhall** [comment]
Seems reasonable.  Let's ensure we aren't conflicting across the various IdP's though.  There were several situations where (for example), emailaddress was in multiple schemas.   If the claim root (e.g. emailaddress) is in multiple schemas, and they are different values, what do we do?

**Comment by danderson00** [comment]
Now I remember briefly discussing this, that's why we didn't normalize them all into a single object. I'll have a think about simplifying it a bit.

**Comment by danderson00** [comment]
@madgrizzle I've done a bit of spelunking and realized that this approach works fairly well. Each provider has its own set of claims, e.g. emailaddress, and normalizing these onto the object for each provider should be fine, it's unlikely that there will be duplicates of the same claim type coming out of each provider. If there is, last in wins, but the original full claim type (e.g. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name) will still be available on the object. I also added a section to denormalize the urn: based claims onto the provider object.

As part of this investigation, I created a document describing the exact responses from the /.auth/me endpoint. You might find this useful - https://github.com/danderson00/auth/blob/master/properties.md.

This isn't released yet, but is merged in. You can see the pull request linked above.
