### ISSUE TITLE
context.data.execute(updateQuery) returns null

### ISSUE THREAD

**Issue by edwinlxl** [Azure/azure-mobile-apps-node#464]
I also try the sample, custom-api-sql-stmt, the records did get updated, but the results from the then function is undefined.

I need to update the table with a query like 'UPDATE mytable SET mynumber = mynumber + 1 WHERE id =@id', I need the updated result from the query.

**Comment by danderson00** [comment]
This is the expected behavior. SQL UPDATE statements do not return result sets. You need to explicitly select the results you want. You can either execute two statements, or use a batch like:

    UPDATE mytable SET mynumber = mynumber + 1 WHERE id =@id; SELECT * FROM mytable WHERE id = @id

Keep in mind that SQLite does not support batches of statements.
