### ISSUE TITLE
Docs for dataConfiguration do not include function version of provider

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#467]
The docs for dataConfiguration and configuration/DataProviders both state that the provider is a string, corresponding to a supported data provider, with 'mssql' and 'sqlite' being the only supported ones.  I believe the string can be the name of a directory / JS file (for providers in the current directory) or a function (e.g. from a require)  I'm assuming that [this](https://github.com/Azure/azure-mobile-apps-node/blob/master/src/data/index.js#L22) would mean I could do something like:

```
var provider = require('azure-mobile-apps-docdb')(config);
var mobileApp = zumo({ data: { provider: provider } });
```

**Comment by danderson00** [comment]
Close - as discussed, the provider object set to data: { provider: provider } should be a function that accepts a configuration object. I'll update the doco.
