### ISSUE TITLE
Specifying a connection string in data configuration forces mssql provider

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#500]

**Comment by danderson00** [comment]
@adrianhall I can no longer repro this. I remember you ran into this when working on your DocumentDB provider. Can you still repro?

**Comment by adrianhall** [comment]
I can still repro.

1. Download adrianhall/azure-mobile-apps-documentdb-driver from GitHub
2. Download adrianhall/azure-mobile-apps-docdb-test from GitHub
3. Set up a DocumentDb service in Azure
4. Set up an azureMobile.js as follows:

```
var docdbDriver = require('../azure-mobile-apps-documentdb-driver');

module.exports = {
    data: {
        provider: docdbDriver,
        connectionString: 'AccountEndpoint={your-docdb-host};AccountKey={your-docdb-key};'
    },
    logging: {
        level: 'verbose'
    }
};
```

5. npm install in docdb-test
6. npm link ../azure-mobile-apps-documentdb-driver
7. npm start

**Comment by danderson00** [comment]
Finally got it. Had to do with the order that configuration was loaded. Fix was:

![image](https://cloud.githubusercontent.com/assets/1265935/24972937/f087552c-1f71-11e7-8cd0-495105c3646e.png)

Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/2a4fc3dcd94b865254b9f42e2e221936269ec435
