### ISSUE TITLE
getIdentity throws error if using custom domain

### ISSUE THREAD

**Issue by jsandersrocks** [Azure/azure-mobile-apps-node#503]
If using a custom domain the code will use the azurewebsites.net audience, however, the aud and iss of the the custom domain is what should be what should be used: "iss":"https://jsandersrocks.com/","aud":"https://jsandersrocks.com/"

Application has thrown an uncaught exception and is terminated:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\azure-mobile-apps\src\auth\getIdentity.js:35:55)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
2016-11-07T16:25:39  PID[8240] Warning     JWT validation failed: IDX10214: Audience validation failed. Audiences: 'https://jsandersrocks.com/'. Did not match:  validationParameters.ValidAudience: 'https://jsandersrocksprod.azurewebsites.net/' or validationParameters.ValidAudiences: 'null'.

Workaround:
Override aud and iss on app start up:

var mobile = azureMobileApps({
    // Explicitly enable the Azure Mobile Apps home page
    homePage: true
    
});

// Import the files from the tables directory to configure the /tables endpoint
mobile.tables.import('./tables');

// Import the files from the api directory to configure the /api endpoint
mobile.api.import('./api');
mobile.configuration.auth.audience="https://jsandersrocks.com/";
mobile.configuration.auth.issuer="https://jsandersrocks.com/";

Optionally specify an appsetting and set this in the portal and use rather than hard coding this.

**Comment by danderson00** [comment]
We should be able to configure this automatically from the WEBSITE_HOSTNAME environment variable. Thanks for the report!

**Comment by mikejohanson** [comment]
Hey @danderson00, something I've noticed as I've begun to deploy and use the swap mechanism in Azure. the WEBSITE_HOSTNAME is swapping too thus invalidating the jwt everytime I do a swap. I get a 401 for requests with the error: 
```
{"name":"JsonWebTokenError","message":"jwt issuer invalid. expected: [https://[mobileapp].azurewebsites.net"}
```
and then swapping again would give

```
{"name":"JsonWebTokenError","message":"jwt issuer invalid. expected: [https://[mobileapp]-[slot].azurewebsites.net"}
```
I tried setting the iss property to my custom domain when signing the token but it still expects the WEBSITE_HOSTNAME property. Any way around this?

**Comment by mikejohanson** [comment]
@danderson00 Nevermind, I realized I could set the issuer when starting up ```azureMobileApps({})``` and that seems to have fixed it. That being said, The above might be an issue for other things, that the WEBSITE_HOSTNAME property is not "sticky" when swapping slots.

**Comment by danderson00** [comment]
This should already be resolved - the audience and issuer are already [set](https://github.com/Azure/azure-mobile-apps-node/blob/master/src/configuration/from/environment.js#L99) from WEBSITE_HOSTNAME. There was an issue with the order that configuration was loaded such that if the custom audience and issuer were specified in an `azureMobile.js` configuration file, it would be overridden by environment settings.

@mikejohanson As far as deployment slots are concerned, I'm not sure there is a simple solution here, aside from explicitly setting the audience and issuer in configuration. We don't have control over the WEBSITE_HOSTNAME value, it's provided by Azure websites. We could attempt to detect that the hostname contains a slot name, but I don't think there is a reliable way to do this as we also can't control the slot names. If you have any thoughts on this, let me know.
