### ISSUE TITLE
Registering client for push fails due to an invalid tag

### ISSUE THREAD

**Issue by m-andersen** [Azure/azure-mobile-apps-node#508]
I'm using latest azure-mobile-apps 3.0.2 and I have an Android client that is registering itself with push to the node server. This is normally done as part of the mobile apps SDK for Android and has been working fine. I discovered recently that it sometimes comes up with an error, and I don't know how critical it is, but for sure it doesn't look like it should be there. This is the output

PUT /push/installations/dfad096c-5956-407e-99eb-169504562abc
. . .
2016-11-27T20:23:23.358Z - error:  Error: 400 - Installation validation failed with following error(s):

An invalid tag(s) ',_UserId:sid:3e2d36c26fc1a21973ddae5e8418bc0b' was supplied. Valid tag characters are alphanumeric, _, @, -, ., : and #..TrackingId:f4698ddb-178c-4bd2-add8-a3d9327f09ff_G12,TimeStamp:11/27/2016 8:23:23 PM
    at Function.ServiceClient._normalizeError (D:\home\site\wwwroot\node_modules\azure-common\lib\services\serviceclient.js:814:23)
    at NotificationHubService.ServiceClient._processResponse (D:\home\site\wwwroot\node_modules\azure-common\lib\services\serviceclient.js:455:41)
    at Request.processResponseCallback [as _callback] (D:\home\site\wwwroot\node_modules\azure-common\lib\services\serviceclient.js:213:35)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:965:12)

As the client doesn't send anything the error must be somewhere in node SDK.
Can anybody please check what is happening? The comma in front of _UserId is something the SDK has done I believe. But why I don't know.
I hope this is a known issue and there is a fix on the way. 

Can this make push notifications to the client stop working?
If I delete all client app data and do a re-registering after login it seems to work.

**Comment by adrianhall** [comment]
Are you using / linking via the new Push blade in your App Service?

Can you provide your site name so we can take a look under the covers?

**Comment by m-andersen** [comment]
Im not sure what you refer to. In my mobile app there is the push setting. I haven't touched that since I enabled push. I will send you a separate message with more details.

**Comment by adrianhall** [comment]
From the email: Something must have changed.  We don't update the code, and it is clearly executing the node push handler.

We have an ongoing push registration issue that is slated to be fixed on the site by 12/16.  In this case, you log onto the Azure portal, go to your app service, and use the Push menu item to configure push (instead of doing it in code).  Our service takes over and handles push registration for you.

I'd recommend that as issue https://github.com/Azure/azure-mobile-apps-node/issues/507 is going to remove the push endpoint anyways, in preference of the service.

**Comment by m-andersen** [comment]
How do you maintain backwards compatibility if you remove the registration endpoint?
I have previously used the push menu to enable the service. What is changed compared to previous? But more importantly, how do I proceed fixing my issue?

**Comment by adrianhall** [comment]
#507 is listed as a breaking change.  We are removing it in favor of a compatible push handler. If you decide to upgrade your server code, you will also need to configure the push handler in the Azure portal.

As to your issue - something in your code must have changed.  We don't alter the code on your behalf, and the error is indicative of a change in the code.  Back out whatever change you made to make it fail.

**Comment by m-andersen** [comment]
Do you mean changes on client side or server side?

From which azure-mobile-app node SDK do you change the push system? Is it described somewhere how it then will work?
I must admit that I have been upgrading azure SDK on server without giving it much thought on dependencies - not obvious to me the changes between releases and what it means to the server or client SDK. Better links or details on dependencies would be very much appreciated.

**Comment by adrianhall** [comment]
The push registration system is fairly straight forward.  You can call `client.RegisterAsync()` within the client - this does a `PUT /push/installations/<installationid>` to the backend with the content being a Notification Hubs installation formatted as JSON.  The backend can either be the App Service Push endpoint (enabled as I described) or the push endpoint within the node backend (which hasn't changed in a long time) or your own code.  If you are using the App Service Push, the tags contained within the submitted installation must be in the allowed list (which you set up when configuring App Service Push).  If using the node SDK version, then tags are stripped out.  If you use your own code, then it's up to you what to do.

So, the problem could be in your client or your server, or in the configuration of your App Service.  Thus far, I've only seen the error, which indicates that what you are submitting is causing an error in the node SDK.  

Perhaps you could actually show your code and configuration?

**Comment by m-andersen** [comment]
I use android client Azure SDK. I call this to register push:
NotificationsManager.handleNotifications(ctx, PUSH_GCM_SENDER_ID, <MyClass>);

In my service I do the final registration - following the TodoList examples:
mClient.getPush().register(gcmRegistrationId);

The latter one calls PUT /push/installatinos/<id>, which has been working fine. This push endpoint is hidden from me as it is part of Azure SDK and the node express stuff I guess. I solely rely on that is done automatically for me. 

After I have re-connected my mobile app to the notification service, I get a serious crash during push registration as mentioned above

2016-11-29T22:42:16  PID[17160] Critical    System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.AppService.Push.PushRequestHandler.<HandleCreateOrUpdateInstallationAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Push.PushRequestHandler.<HandlePushRequestAsync>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Push.PushModule.<OnPostAuthenticateRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Authentication.HttpModuleDispatcher.<DispatchAsync>d__13.MoveNext()
2016-11-29T22:42:16  PID[17160] Information Sending response: 500.79 Internal Server Error

I really don't get it what is going on. I might not be into all details of how it works, so any ideas is welcome.

**Comment by adrianhall** [comment]
The crash stack trace that you just published indicates that you have already set up the App Service Push.  This is completely different from the node SDK.  It's part of the App Service configuration.

You can disable the App Service Push and reinstate the old push.  See https://github.com/Azure/azure-mobile-apps-net-server/issues/170 and check near the bottom for a comment about disabling App Service Push from @jwallra

**Comment by m-andersen** [comment]
I will try to roll it back with the described changes. Thanks.
I still don't understand why app service push configuration is being changed all of a sudden without notification to users. And especially the dependencies needed. Not a nice surprise for us trying to use Azure platform

**Comment by m-andersen** [comment]
Roll back as mentioned in the id above works. But, I still have the original issue.
Not sure how I can fix this, as I don't know exact when this problem began.

**Comment by adrianhall** [comment]
The app service push changes were designed to be transparent.  There is a bug - we are in the process of rolling out a change to fix the bug.  That bug wasn't what you first reported.

Since you are in charge of the backend code as well as your mobile app, it's incumbent on you to check dependencies on upgrades.  We revise the dependencies all the time to handle security bugs, better performance, etc.  These are rolled into new releases of the Azure Mobile Apps SDKs.  Sometimes there are breaking changes and sometimes not.  If there are breaking changes, we bump the major revision.  This is in line with many other open source projects.

**Comment by m-andersen** [comment]
I saw in Azure mobile services documentation that it should be possible to do online node.js debugging / single-step directly on the server. I enabled the different flags but the page never loads. Does this work at all on mobile apps?
So far no luck in reverting node azure-mobile-apps version. Super strange

**Comment by adrianhall** [comment]
You should not be reviewing azure mobile services docs - app service is a different service.  You need to check out App Service information.

**Comment by danderson00** [comment]
Sorry for joining late - it is possible to debug remotely, but I've struggled to get it working myself. http://willi.am/blog/2015/07/24/debugging-nodejs-azure-web-apps/ should be the right steps.

**Comment by bbougot** [comment]
Still not working.
