### ISSUE TITLE
Urgent Clarification - Change connection dynamically

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-node#509]
Hello,

Need to be sure that **I can o cannot** change the connection dynamically depending on a userclaim or anything else on the request. The different databases would have the same structure. 

- Is it possible?
- How can I implement this with azure mobile apps?

If it's too much work, I might need to stop using mobile-apps, and do something myself, because I cannot maintain one endpoint for each db (about 50). (it's the way our BL works)

It was MY fault that initially this requirement was not taken into account.

Thanks

**Comment by andreujuanc** [comment]
I just tried to "throw some arrows" and I think I hit something! 

```
function setConnection(context){
    context.configuration.data.database = 'Des_Mobile';
    return context.execute();
}
```

And It did changed the connection. But wondering if this is the right approach?

**Comment by andreujuanc** [comment]
OK, i got it working:

First pass the config in the <table>.js file like so:
```
function getDatabase(dbName){
    return {
           provider: 'mssql',
            server: 'contoso.com',
            port:1433,
            database: dbName,
            schema:'dbo',
            user: 'some user',
            password: 'lepassword'
    };
}
```

in execute.js:
```
 return getNewConnection()
        .then(executeRequest);

    function getNewConnection(){
       //Need to see how to close it without issues. Or is it poolled?
        // if(connectionPromise){
        //     connectionPromise = undefined;
        //     return connection.close().then(getNewConnection);
        // }
        connection = new mssql.Connection(config);
        connectionPromise = connection.connect()
            .catch(function (err) {
                connectionPromise = undefined;
                throw err;
            });
        return connectionPromise;
   }
```

index.js of mssql data provider:
```
var tableAccess = function (table, context) {
        configuration = context && context.configuration && context.configuration.data ?   context.configuration.data : configuration ;
```

This works, for now.

Ideas???

**Comment by adrianhall** [comment]
We don't have such a feature on the roadmap, and there are several reasons why you wouldn't want to do this - connection pooling being one of them.  There are likely to be several corner cases to be tested in your scenario.  

Mentioning @danderson00 as he has a better understanding of the code base as a whole.

**Comment by andreujuanc** [comment]
Thanks @adrianhall ! appreciate your reply. Indeed there are lots of testing to do on my side of things.
@danderson00  Any tip would be great! Hope I can get some code insight from you!

**Comment by danderson00** [comment]
Some time ago, we discussed having multiple data connections per app, but have not had the demand for it. There should be no real reason why you can't create a new instance of a data provider with a new configuration object for different data sources, something like:
```
var data = require('azure-mobile-apps/src/data')({ data: { /* connection options */ } });
data({ name: 'tableName' }).read().then(/* */);
```
We are rather stretched for resources at the moment, it is unlikely we will have the time to implement this for quite a while. If you end up implementing a solution that you're happy with, please feel free to submit a PR, I'm sure other users would benefit from your solution, too!

**Comment by andreujuanc** [comment]
@danderson00  Thanks! I still dont know the way to implemented, if coded as part of mobile-apps-node or ,as a plugin, (found the code for that) , or any other way, any recommendations on this matter will be apreciated. 

Cheers

**Comment by danderson00** [comment]
For reference - https://github.com/Azure/azure-mobile-apps-node/issues/290

**Comment by danderson00** [comment]
Yeh, unfortunately it's not trivial. As quick implementation is probably to have a simple module that serves as your "factory" for data providers - export a function that takes a table name and data source name and return a data provider that uses the configuration for the data source name.

**Comment by andreujuanc** [comment]
@danderson00 Thanks mate, will try that way.

**Comment by andreujuanc** [comment]
@danderson00 If I reuse the configuration variable as placeholder of my multiple connection while process execution. Would i be getting into race conditions? 

It's been bit hard to implement something "sexy" since some code is ambiguous, especially the word, context, context.data, configuration, configuration.data, in some places those are the same, or some other times, they are different instances.

I need to set the data configuration per request. So that way there would be no issues.

**Comment by danderson00** [comment]
I would strongly recommend against trying to reuse the same configuration object, it will invite subtle bugs into your code. Create a new instance for each data provider.

As far as ambiguity with provided objects, the configuration object should always be the same instance, though some specific modules may only store their specific part of the configuration. the context object will be a new instance per request.

Can you provide some examples of where this isn't the case? We can look at making it more consistent and easier to work with.

**Comment by andreujuanc** [comment]
Sure, man. I already tried and got a RC xD

I'm currently implementing something better done. Thats why im checking out all the code, and found some weird namings.

For example:
mssql/index.js => module.exports = function (configuration) 
But it's not the whole config, just the configuration.data part. Which makes sense because it's mssql instance, but i'ts not quite right.
And in mssql/execute. => function (config, statement) where config is configuration.data as well.

Right now I dont remember more, but if you feel it's something that we can improve, then might start writing down those "issues" so we can work on them.

**Comment by andreujuanc** [comment]
I GOT IT!!!
FINALLY!!
It was hard, because the connection depends on user current "facility" (from headers), then i have to go to a central db twice, decode connection string, and do all this data context thing.

I do know that my final solution is not the best, but I did found some stuff that might get my attention, so probably i will fork the project C:

I tested 3 clients in different PCs, doing 50 queries after the other, each to different DB, and those 3 clients querying at the same time worked as expected!! 

Now i need to work a bit on the connection side of things, and check pooling and so on.

C:

**Comment by andreujuanc** [comment]
This is part of my solution: let me know if it can cause any issue:
middleware/executeOperation.js
```
 var result = setDatabase(context); // my method returns new provider with user's db connection string
        if (promises.isPromise(result))
            result.then(executeOperation);
        else
            executeOperation(result);

        // if a custom operation has been defined, execute it
        function executeOperation(dataprovider){
            context.data = dataprovider; // IS THIS FINE?
            if (operations && operations[operation]) { 
                var results = operations[operation](context);

                if (promises.isPromise(results))
                    results.then(setResults, next);
                else
                    setResults(results);
            } else {
                execute().then(setResults, next);
            }
        }
```

I know that context.data is set in createContext.js, but it's set to a "global", already created one. What i do is overite it, so the execution goes "transparent" for each table. 🍶
