### ISSUE TITLE
Socket IO integration in existing azure-app-node-api structure

### ISSUE THREAD

**Issue by Anshdesire** [Azure/azure-mobile-apps-node#510]
I have app-node instance and has created so many Apis. Now need to add socket.io chat as well.
I added this code via a file which successfully works 

`module.exports = function(configuration, app, io) { io.on('connection', function(socket) { ... }));`

What i want is to access same azure db as well which i am using for other apis. 
I am not able to get context here.

How to get context to execute custom query here.

**Comment by danderson00** [comment]
Responded in gitter channel - context object is created in middleware that is not executed on sockets. Refer to https://github.com/Azure/azure-mobile-apps-node/blob/master/src/express/middleware/createContext.js

**Comment by tienvv1234** [comment]
Hi @danderson00, How can I use the createContext. I am not able to get the context in socket too. Could you give me an example to create Context

**Comment by danderson00** [comment]
Hi @tienvv1234, I no longer work on the Mobile Apps team. I believe @elamalani is the current product manager.

**Comment by tienvv1234** [comment]
@danderson00 Thank you for your reply, Hi @elamalani Could you give me an example of this
