### ISSUE TITLE
Should access:anonymous validate JWT?

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-node#516]
Given this configuration: `"get": { "access": "anonymous" }`. And an expired JWT:

Currently it does validate the JWT and does not allow anonymous access to api. 

Should that endpoint validate the JWT, or on the other hand, let the request pass through?

**Comment by danderson00** [comment]
Is this on a Mobile App hosted on Azure? If so, it will depend on how you have Authentication / Authorization configured in the portal, specifically the `Action to take when request is not authenticated` setting. This is beyond the control of the Mobile Apps SDK.

If you can reproduce this locally, can you post some more details? I'd like to try and reproduce the issue.

**Comment by andreujuanc** [comment]
@danderson00  I'm developing this locally. Sorry I forgot to specify that I was using **custom authentication** 
So i started following the sample for custom authentication. Works fine. Code on my client is using azuzre apps client js. 

I did "inject" on my client side, the currentUser for azure, so that way the token is sent to the endpont on every request.

Issue is not with client side, since I can reproduce it with PostMan.

Get the sample: https://github.com/Azure/azure-mobile-apps-node/blob/master/samples/custom-authentication/api/login.js

1. in postman Login, and copy the token. 
2. Invalidate token (wait for expire , change the expire property so its only valid for some seconds)
3. Add X-ZUMO-AUTH to headers with respective token. 
4. Change TodoItems json config to allow anonymous users to read the table:  `"get": {    "access": "anonymous"  },`
5. Finally make a GET request just after the token is not valid anymore , It should give you this error:

```
{
  "name": "TokenExpiredError",
  "message": "jwt expired",
  "expiredAt": "2016-12-14T01:07:54.000Z"
}
```

I'm sure this is not a bug. But it's more like What the correct behaviour should be ?

**Does an Invalid JWT token revokes any access for a client to anonymous api?**

**Comment by danderson00** [comment]
Ahh, OK. This is currently by design - any OAuth token sent to the service is validated, regardless of whether the endpoint requires authentication. I'll have a look at the work required to make the SDK only validate tokens for endpoints requiring authentication and get back to you.

**Comment by andreujuanc** [comment]
Ok ok! Great. 
I was curious because in some cases (besides my scenario) other users can have similar issues for offline sync. If they are offline, generate data, then never sync or open app (cordova app for example) the token can expire before the user opens it and starts to sync., and it wont work since endpoint blocks the request with expired token. 

Just let me know if it's doable, or can be marked at least as feature request. That way I can implement some patch myself until ti's officially done. (Or merged from my solution)

Thanks mate

**Comment by danderson00** [comment]
Fair point. My initial thought for expiring tokens is to use refresh tokens. There are a bunch of resources in this area:
- https://azure.microsoft.com/en-us/blog/mobile-apps-easy-authentication-refresh-token-support/
- https://cgillum.tech/2016/03/07/app-service-token-store/
- http://stackoverflow.com/questions/36289458/requesting-azure-app-service-authentication-refresh-tokens

**Comment by andreujuanc** [comment]
Yeap, maybe I can intercept responses on my client and check for unauthorised statuses and if user is logged in then refresh the token. For sure it´s a solution I will try before messing with endpoint.

If you don't find this feature interesting then we can proceed to close the issue :)

As always, thanks for replying mate!

**Comment by adrianhall** [comment]
I've blogged about using filters/delegating handlers in the past to handle the refresh logic.  Most recent is a C#/.NET example in my book at https://aka.ms/zumobook.  You can find the implementation here: https://github.com/adrianhall/develop-mobile-apps-with-csharp-and-azure/blob/master/Chapter2/TaskList/TaskList/Helpers/AuthenticationDelegatingHandler.cs

**Comment by SteveALee** [comment]
I was just reading this article and linked blog post on refresh tokens - very useful for context and perhaps @adrianhall's code?
https://auth0.com/docs/tokens/refresh-token

**Comment by andreujuanc** [comment]
@adrianhall Exactly what you did in that C# example is what I was thinking on do myself. At least I see I'm doing it the right way :)

Just need to see how I'm going to implement it in Azure Mobile Client Js.

@SteveALee Thanks for that link, useful for me to implement that on my custom authentication logic.

I will close this issue, since I expired tokens are more normal thing than I previously thought.

Thanks everyone.
