### ISSUE TITLE
.catch not functioning as expected

### ISSUE THREAD

**Issue by drumrigj** [Azure/azure-mobile-apps-node#518]
We followed the pattern on the node backend from the /samples/push-on-insert/tables/TodoItem.js (seen below). Code in the .catch gets executed but then goes into LaLa land until we get a timeout where previously, on the consuming end for example, if we ran into an id conflict on an insert we would immediately receive a ```MobileServiceConflictException```, but now it hangs for the duration of the timeout. I'm not saying there is a problem with this sample, i'm just trying to figure out what changed where and if there is different suggested pattern to handle the exceptions from a ```context.execute()```. This worked previously, but as of Nov/Dec 2016 timeframe(???), it changed. If we remove the .catch it functions as expected we just lose logging and insight for debugging purposes.

Anybody else seeing this?
Thoughts @adrianhall ?? Thanks

```csharp
return context.execute()
   ...
   .catch(function(error) {
      //Did something change here that exceptions are no longer returning properly
   };
```

**Comment by adrianhall** [comment]
Do you re-throw the error in the catch?  The pattern should probably be:

```
return context.execute().catch(error => {
    // Do something
    throw error;
});
```

**Comment by adrianhall** [comment]
Closing due to no response.
