### ISSUE TITLE
Push Notification API Documentation

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-node#521]
Hello guys,

With some spare time, can someone update api docs for push related stuff? https://azure.github.io/azure-mobile-apps-node/

There is an example that uses createOrUpdateInstallation, another uses patchInstallation and docs only states putInstallation. Bit confusing.!

Also user tags wont work unless registered manually using js client. I just think the js client is not sending the user when registered and not being associated with the installation. (I will report this when confirmed to the JS Client repo)

The only example using client is a .Net one, which should be a JS client, since this is node backend. 

For me it's ok, I don't need this, since I just spend like 6 hours figuring everything out, but it'd be nice to have it ready and polish for new users.

Warm Regards

**Comment by adrianhall** [comment]
There is no push related docs in the referenced URI, aside from a pointer to the official Notification Hubs SDK (which obviously covers ALL the ways to do push - not just the ones appropriate to Node or JavaScript).  Is that the docs you are referring to? 

If not, we need a pointer to the exact page.
If so, then you should open a UserVoice on feedback.azure.com with Notification Hubs.

**Comment by adrianhall** [comment]
Based on lack of feedback, closing.
