### ISSUE TITLE
No Plugin Support

### ISSUE THREAD

**Issue by iamchairs** [Azure/azure-mobile-apps-node#522]
Migrating old mobile apps services to the new apps service. We have a lot of code in the old mobile apps service that would be a pain to migrate. So to handle this situation the most effectively I would like to write a middleware after `createContext` and before the api is called. This middleware would shim legacy support back in, and going forward we'd use the new endpoints.

I was looking through the source and noticed `customMiddlewareRouter` was used. This would work fine for me, The problem is, it gets it's list of plugins from a module called `knownPlugins`, and a peak into the source of that files shows-

https://github.com/Azure/azure-mobile-apps-node/blob/master/src/express/knownPlugins.js
```
// ----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// ----------------------------------------------------------------------------

module.exports = function (configuration, logger) {
    return ['azure-mobile-apps-files'].reduce(detectPlugin, []);

    function detectPlugin(plugins, name) {
        try {
            var pluginModule = require(name);
            try {
                plugins.push(pluginModule(configuration, logger));
                logger.info('Loaded plugin ' + name);
            } catch (ex) {
                logger.error('Found plugin ' + name + ' but failed to load: ', ex);
            }
        } catch(ex) {
            logger.silly('Not loading plugin ' + name + ': ' + ex.message);
        }
        return plugins;
    }
}
```

It's hardcoded to return `azure-mobile-apps-files` if it exists, or nothing at all. Can this be updated to accept a `plugins` setting in the config?

**Comment by danderson00** [comment]
You can mount custom middleware that is executed after createContext but before custom API or table middleware is executed by calling `use` on the mobile apps instance:
```
var app = require('express')();
var mobile = require('azure-mobile-apps')();
var customMiddleware = require('./middleware/custom');

mobile.tables.add('todoitem');
mobile.use(customMiddleware);
app.use(mobile);
```

Please feel free to reopen this issue if this does not solve your problem!

**Comment by iamchairs** [comment]
I don't believe that is true.

in `src/express/index.js`.

```
mobileApp
        .use(middleware('version'))
        .use(middleware('createContext'))
        .use(middleware('authenticate'))
        .use(customMiddlewareRouter)
        .use(configuration.notificationRootPath || '/push/installations', middleware('notifications'))
        .use(configuration.apiRootPath || '/api', apiMiddleware)
        .use(configuration.tableRootPath || '/tables', middleware('apiVersionCheck'), tableMiddleware, middleware('renderResults'));
```

I need to add middleware where `.use(customMiddlewareRouter)` is called.

**Comment by danderson00** [comment]
Calling the `use` function on the mobile apps instance [mounts the provided middleware](https://github.com/Azure/azure-mobile-apps-node/blob/master/src/express/index.js#L86) onto the customMiddlewareRouter, so yes, any middleware you pass to the `use` function is mounted at this point.

**Comment by iamchairs** [comment]
Oh- Sure does. Thanks.
