### ISSUE TITLE
comparison of records on timestamp

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-mobile-apps-node#523]
I’m using azure-mobile-apps SDK v 3.0.2 in a node.js project, as taken from the sample project. Code is the following
```
var queries = require('azure-mobile-apps/src/query');       
var query = queries.create(“tableName");
query.includeDeleted().where( function(timeStamp) {
    return  (this.updatedAt > timeStamp);
},  timeStamp);

req.table(“tableName").read(query).then( function(listResults) {.....

```

This is translated into SQL statement

WHERE (((([uniq_user_id] = @p1) OR ([household_id] = @p2)) AND (**[updatedAt] > @p3**))  ....

which looks correct. 

For Datetime datatype , Accuracy  is Rounded to increments of .000, .003, or .007 seconds.
The following article has the information - 
https://msdn.microsoft.com/en-us/library/ms187819.aspx

Verification  can be done using the following query – 

select 
convert(datetime, '2017-02-07T17:03:52.070Z') as [70], 
convert(datetime, '2017-02-07T17:03:52.071Z') as [71], 
convert(datetime, '2017-02-07T17:03:52.072Z') as [72], 
convert(datetime, '2017-02-07T17:03:52.073Z') as [73],
convert(datetime, '2017-02-07T17:03:52.074Z') as [74],
convert(datetime, '2017-02-07T17:03:52.075Z') as [75],
convert(datetime, '2017-02-07T17:03:52.076Z') as [76],
convert(datetime, '2017-02-07T17:03:52.077Z') as [77],
convert(datetime, '2017-02-07T17:03:52.078Z') as [78],
convert(datetime, '2017-02-07T17:03:52.079Z') as [79]

Result – When you see the result you can only see 0.70,0.73 or 0.77.

 
![image](https://cloud.githubusercontent.com/assets/1486808/22905487/02f97a76-f206-11e6-9f8f-0158c8d9c7dd.png)

More accuracy can be obtained using datetime2 datatype.
Datetime2 datatype has an accuracy of 100 nanoseconds.
The following article has the information – 
https://msdn.microsoft.com/en-us/library/bb677335.aspx

Verification  can be done using the following query –
select 
convert(datetime2, '2017-02-07T17:03:52.070Z') as [70], 
convert(datetime2, '2017-02-07T17:03:52.071Z') as [71], 
convert(datetime2, '2017-02-07T17:03:52.072Z') as [72], 
convert(datetime2, '2017-02-07T17:03:52.073Z') as [73],
convert(datetime2, '2017-02-07T17:03:52.074Z') as [74],
convert(datetime2, '2017-02-07T17:03:52.075Z') as [75],
convert(datetime2, '2017-02-07T17:03:52.076Z') as [76],
convert(datetime2, '2017-02-07T17:03:52.077Z') as [77],
convert(datetime2, '2017-02-07T17:03:52.078Z') as [78],
convert(datetime2, '2017-02-07T17:03:52.079Z') as [79]

Result – If you see the result we are getting the values we are passing to convert- 
![image](https://cloud.githubusercontent.com/assets/1486808/22905514/1ace5964-f206-11e6-9ec0-97b07746ffc2.png)

 I think we need to change how we compare timestamp and use datetime2 instead

**Comment by danderson00** [comment]
@prashanthmadi We use the datetimeoffset type for date fields (specifically datetimeoffset(7) for the updatedAt column), which provides the same precision as datetime2. Can you provide more information about where you are seeing the drop in precision?

**Comment by prashanthmadi** [comment]
@danderson00 Thanks for looking into this issue

Below is the sample code
```
var queries = require('azure-mobile-apps/src/query');       
var query = queries.create(“tableName");
query.includeDeleted().where( function(timeStamp) {
    return  (this.updatedAt > timeStamp);
},  timeStamp);
```
Is there a better way of fetching records that involve where clause based on timestamp ?

**Comment by danderson00** [comment]
I'm not sure where the drop in precision is occurring in this case. The updatedAt column will be datetimeoffset(7), so the underlying type supports full precision. It's possible that the underlying SQL provider (tedious) might be causing an issue, but it's hard to tell.

Are you able to consistently reproduce the issue, i.e. do you have an existing table that contains a set of records with specific updatedAt values, and are able to execute a query that incorrectly excludes some of the records?

**Comment by danderson00** [comment]
@prashanthmadi Did you end up getting more info about this issue, can you provide a set of steps to repro?

**Comment by prashanthmadi** [comment]
sorry for delay i will work on it today

**Comment by danderson00** [comment]
@prashanthmadi From external correspondence, my understanding is that this is an issue with SQL Azure. Please feel free to reopen this issue if this is not the case. Thanks!
