### ISSUE TITLE
Configurable System Columns

### ISSUE THREAD

**Issue by iamchairs** [Azure/azure-mobile-apps-node#524]
We are migrating from the old mobile services to the new apps services. In addition to this, we are migrating a lot of tables to Easy Tables.

During migration I noticed the system columns were renamed. From `__deleted` -> `deleted`, etc. Our systems aren't setup to handle this change and a refactor would be required for our server and client side applications.

For that reason, I went down the path of configuring Easy Tables to use our naming conventions, but it appears the new naming convention is hardcoded.

Could this be updated to allow system columns `deleted`, `version`, `createdAt`, and `updatedAt`, to be configurable?

This is also something I can create a pull request for.

**Comment by iamchairs** [comment]
Example of hardcoded column names-

https://github.com/Azure/azure-mobile-apps-node/blob/master/src/data/mssql/helpers.js#L142

**Comment by danderson00** [comment]
There is a fair bit of work involved in making system column names configurable - it's not on the road map at the moment. As an easier solution, you can run the SQL script [here](https://github.com/Azure/azure-mobile-apps-node-compatibility/blob/master/static/createViews.sql) to generate views for each of your tables that map system column names to the appropriate values.

**Comment by iamchairs** [comment]
Views! I didn't know about Views!

Thanks.

**Comment by danderson00** [comment]
Hope it helps! Feel free to post here if you are having trouble getting things working.

**Comment by iamchairs** [comment]
So this looked promising but there is an issue with this. Views sharing the table name need to be given a different schema and queries need to explicitly reference that schema. So we can't have two naming conventions coexisting.

Unless I'm using this incorrectly.

`SELECT * FROM MyTable WHERE _deleted = 0`
Is not the same as.
`SELECT * FROM MyTable WHERE deleted = 0`

**Comment by danderson00** [comment]
Tables in the Mobile Services database will have been created on a database schema name that corresponds with the name of the Mobile Service. The views script linked here creates tables in the dbo schema. There should be no conflicts.

**Comment by iamchairs** [comment]
You say that but here's what I'm seeing. Lets say my app service is called `my-app`. So you'd think all tables should be in the schema of `[my_app].[MyTable]`. This is how querying works, but creating tables through the `mobileApp.tables.create` api creates new tables under `[dbo]`. Additionally, `mobileApp.tables.import` creates a `[dbo]` version of every table I have defined. I could manually configure the schema in the table js files, but that would mean the source would need to be aware of it's environment, which is not ideal.

**Comment by danderson00** [comment]
If you are pointing your Mobile App at the same database that your Mobile Service uses, you will need to create the views first. Mobile Apps will look for a table in the dbo schema, if it doesn't find it, it will create it - if the view has already been created in the dbo schema, it will use that, i.e. it won't create a new table.

To put it another way - delete all of the tables in the dbo schema that Mobile Apps created - keep all the ones under the `my_app` schema. Execute the createviews.sql script to create equivalent views in the dbo schema. After you have done this, THEN run your Mobile App and it will consume the views in the dbo schema.

**Comment by adrianhall** [comment]
Might want to use the migration package that @danderson00 created to aid in the migration - it produces an appropriate SQL script.
