### ISSUE TITLE
Better error messages when Push related app settinsg are missing.

### ISSUE THREAD

**Issue by aziel** [Azure/azure-mobile-apps-node#525]
To reduce user unhappiness, it would be better to provide an explicit error message due to missing app settings for Push:
MS_NotificationHubName
MS_NotificationHubConnectionString.

Currently, you'll get a cryptic response:
-- Result: {"Cannot read property 'listRegistrationsByTag' of undefined"}

Would be nice to return a 400 with "The MS_NotificationHubName app setting is null" or "The MS_NotificationHubConnectionString app settings is null" to logs or in the error response.

**Comment by adrianhall** [comment]
Hi @aziel - the Node SDK does not handle App Service Push.  We are actually explicitly ripping push pieces out (and replacing with a stub).  So I don't think this is a bug we will work on.
