### ISSUE TITLE
Enable authorizations configuration of swagger-ui

### ISSUE THREAD

**Issue by rizkyario** [Azure/azure-mobile-apps-node#526]
Hi,
Would it be possible to set authorizations configuration of swagger-ui, so there would be Authorize button shows up on the swagger-ui (attached)
![screen shot 2017-03-05 at 10 12 29 pm](https://cloud.githubusercontent.com/assets/6814254/23591459/17439110-01f1-11e7-8384-47c3dc66fc61.png)

**Comment by danderson00** [comment]
Hi @rizkyario thanks for the feedback! We'll consider the feature and get back to you.
