### ISSUE TITLE
how to use Azure Active Directory authentication

### ISSUE THREAD

**Issue by navneetccna** [Azure/azure-mobile-apps-node#527]
I want to connect database using Azure Active Directory authentication.

Try to find in doc but not getting any thing please help me on that

**Comment by adrianhall** [comment]
The connectivity with Azure Active Directory is documented on the official docs: https://docs.microsoft.com/en-us/azure/app-service/app-service-how-works-readme?toc=%2fazure%2fapp-service-mobile%2ftoc.json - it isn't handled within the Node application, but in App Service.

**Comment by navneetccna** [comment]
I did this setup already but i am still connected to sqlite db not the azure sql server.

**Comment by adrianhall** [comment]
So, you asked about azure AD - not the SQL database.  Please be precise in your needs so we know what the problem is.

To access the SQL Azure instance locally, you need to:
1) Set up the firewall in SQL Azure to allow access from your local instance
2) Set the data section of your azureMobile.js file to point to the right place - this needs the information in the dataConfiguration settings.

**Comment by navneetccna** [comment]
I already told you that i want to connect Azure SQL server and DB using my Active Directory username and password (AD authentication).

**1. Set up the firewall in SQL Azure to allow access from your local instance**
I already did that
**2. Set the data section of your azureMobile.js file to point to the right place - this needs the information in the dataConfiguration settings.**
My configuration in the azureMobile.js file is

`data: {
        provider: 'mssql',
     
        connectionString: 'Driver={ODBC Driver 13 for SQL Server};Data Source=tcp:db.database.secure.windows.net,1433;Database=my_db;Uid={my_ad_user};Pwd={my_ad_password};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=500000;Authentication=ActiveDirectoryPassword',

    },
`

**Comment by adrianhall** [comment]
Your connection string is wrong.  You are using the ODBC connection string.  If you add the SQL Azure instance via Data Connections to an app service in the Azure portal, you can see the connection string through either data connections or application settings.

**Comment by danderson00** [comment]
The underlying SQL Server data provider does not support authentication against AAD (yet). I know the team are working on this feature. Keep an eye on the issue you linked, hopefully it is not far off.

**Comment by navneetccna** [comment]
@adrianhall I got this string from Azure portal

**Comment by adrianhall** [comment]
There are several connection strings - one for ODBC, one for ADO.NET, etc.   You need to use the correct one - not necessarily the first one listed.

If you connect a SQL Azure instance to an App Service instance via the Data Connections, then look at the connection string, you get the right one.

**Comment by navneetccna** [comment]
Yes i know that but i only have AD username password. So i need to use AD method only.
