### ISSUE TITLE
When deploying to Azure after using Easy Tables, static schema isn't updated

### ISSUE THREAD

**Issue by kellylawson** [Azure/azure-mobile-apps-node#528]
I think this is a question but I'm not sure if there is an underlying code related issue.  

I have been using Azure mobile apps and defining my schema through Easy Tables in the portal.  I now need to take more control over my endpoints, and as such have added static table column definitions based on [this](https://shellmonger.com/2016/04/15/30-days-of-zumo-v2-azure-mobile-apps-day-8-table-controller-basics/).

My local database table columns are updated correctly when I start up my local dev server.  However, when I push to my stage environment hosted in Azure (where I was using Easy Tables in the past) my server starts up but the schema is not updated in the database to match my table definition from code.

I have ensured that dynamicSchema is false for the table, and I don't have any application level data configuration - I am using the default.  For table level data configuration, I have the following:

```
table.dynamicSchema = false;

table.columns = {
    firstName: 'string',
    lastName: 'string',
    userName: 'string',
    description: 'string',
    email: 'string',
    authId: 'string',
    authProvider: 'string',
    hasProfilePic: 'boolean'
};

table.databaseTableName = 'User';

table.read.access = 'anonymous';
table.insert.access = 'authenticated';
table.update.access = 'authenticated';
table.delete.access = 'disabled';
```

I am wondering if it is currently possible to switch from using Easy Tables to static schema configuration in code, or if this isn't a use case that was expected.  I can't find any info online about turning off Easy Tables once it's on, and I would not like to drop and re-create all my tables.

**Comment by danderson00** [comment]
Hi @kellylawson, Easy Tables is just a management interface for your tables. What you really mean here is dynamic schema. Your table definition looks spot on, it's likely you are just missing a call to `tables.initialize()` in your app startup code. This function does the schema initialization based on your table definition. Have a look at how it's used [here](https://github.com/Azure/azure-mobile-apps-node/blob/master/samples/static-schema/app.js#L23).

Hope this helps!

**Comment by kellylawson** [comment]
Thanks for the quick reply @danderson00.  I do have the call to initialize in my app.js - I originally used the nodejs template created by azure so it was set up that way, I didn't ever have a dynamic schema.  It looks like so:

```
mobile.tables.initialize()
    .then(() => {
        app.use(mobile);    // Register the Azure Mobile Apps middleware
        app.use('/custom', router(mobile.configuration));
        app.use(errorHandler);
        app.listen(process.env.PORT || 3000);   // Listen for requests
    });
```

It's good to know that what I'm trying to do should work though; I thought maybe there was some magic in Easy Tables that was stopping my schema from being updated in favor of management through the azure interface.  I've connected to my azure database with SQL server management studio and updated the schema manually, and I see the change reflected in Easy Tables.  I'll keep digging and see if what I can find as far as updating the schema in the initialize method.  Knowing this should work is half the battle.

**Comment by danderson00** [comment]
Happy to help! This looks right; provided the table definitions are imported before the call to `initialize`, it should create the specified schema. It might be worth trying to run this on a local machine with the `---logging.level silly` option, it will show you the exact SQL statements that are executed. To be more specific, run the backend locally by running:

    node --debug app.js ---logging.level silly

Let me know if this doesn't work. Once we've got the SQL statements that are being executed, we can figure out what's going on.

**Comment by kellylawson** [comment]
Since my local was working with a local mssql database, I tried running my local against the database in Azure.  I debugged the [updateSchema code](https://github.com/Azure/azure-mobile-apps-node/blob/master/src/data/mssql/statements/updateSchema.js#L12) and saw that the columns comparison worked correctly and the insert to create a new columns was executed.  In this test, the azure database was updated correctly.  

After that worked, I deleted the column from the azure database table, and redeployed my server in Azure.  Again, it didn't update the schema and re-add that column.

So it seems like my local dev server works; I can run it against my local database or against the database in azure, and in both cases the schema is updated correctly.  It's only when my server starts up in Azure that it doesn't seem to update the database schema correctly.  I'll see if I can set that logging level in azure for node and get something useful from there - thanks for the tip.  I'll let you know what I see.

**Comment by kellylawson** [comment]
Looks like setting the MS_MobileLogLevel environment variable through app settings to 'silly' should do the trick.  I'm not sure where to view the resulting log in kudu though.  I'll look some more in the morning.

**Comment by adrianhall** [comment]
Set up diagnostic logs in the app service menu, then (right below diagnostic logs) is Log Stream.

**Comment by kellylawson** [comment]
Yeah I took a look at the diagnostics settings, I realized what was happening.  Application logs was set to enabled but my last applications logs were from a month ago and nothing was showing in Log Stream.  I noticed the note next to the Applications Logs field that says that it will turn itself off after 24 hours, it seems like it did that but didn't disable the setting in the portal UI, so I thought it was still enabled but it wasn't.  There might be a bug in the portal UI there.

Long story short, I get logs now, but I see deployment logs and request logs only, no 'silly' startup logs indicating what is happening with the SQL server requests.  Looking in my kudu environment variables list, I see:

```
MS_DebugMode = true
MS_MobileLogLevel = silly
```

Looking at the azure mobile app service code for configuring from the [environment](https://github.com/Azure/azure-mobile-apps-node/blob/master/src/configuration/from/environment.js#L11), it looks like that should be setting the log level to 'silly'.  I'm trying to figure out why its not...

**Comment by kellylawson** [comment]
I set the logging level in my app configuration like this:

```
    data: {
        provider: 'mssql',
        dynamicSchema: false
    },
    logging: {
        level: 'silly'
    }
```
and locally, I get the logs I am looking for:
```
2017-03-10T18:43:56.205Z - verbose: Adding table definition for Role
2017-03-10T18:43:56.205Z - verbose: Adding table definition for User
2017-03-10T18:46:09.984Z - silly: Executing SQL statement SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @table AND TABLE_SCHEMA = @schema with parameters [{"name":"table","value":"Artist"},{"name":"schema","value":"dbo"}]
2017-03-10T18:46:10.047Z - info: Updating schema for table Artist
```
In azure though, I don't get any of these azure mobile sdk messages on startup in the log stream; I see the initial deployment logs, then I see the request logs, but nothing at startup.  I've been through all the log files I can find on the deployed vm as well and I can't see anything with startup messages from azure mobile, silly level or otherwise.  I'll bang my head against this a bit later on again, and let you know what I find.

**Comment by kellylawson** [comment]
I figured out what was going on with logging - I had a couple of issues.  I had moved all the table definitions from the default location in my source code of /tables to /server/tables, and every request started returning a 401 after that.  The issue of not logging anything from the SDK was resolved by adding the Winston transport in my config; I thought the default console logging should work but it seemed to output nothing.  

Now I'm getting logs, but unfortunately so far they aren't particularly helpful.  The relevant logs at startup for the table that I'm trying to update are the following:

```
2017-03-12T16:17:16.916Z - �[35msilly�[39m: Executing SQL statement SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @table AND TABLE_SCHEMA = @schema with parameters [{"name":"table","value":"User"},{"name":"schema","value":"dbo"}]
2017-03-12T16:17:16.931Z - �[32minfo�[39m: Updating schema for table User
2017-03-12T16:17:16.931Z - �[35msilly�[39m: Executing SQL statement SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @table AND TABLE_SCHEMA = @schema with parameters [{"name":"table","value":"User"},{"name":"schema","value":"dbo"}]
```

There are not logs indicating that it executes a statement to update the table; I'd expect an INSERT here but its not happening.  I'll try adding some logging in the sdk on my deployed environment and see what it is getting back for columns and what it's reading from the table config.

**Comment by kellylawson** [comment]
I spoke too soon.  It looks like it's working now; I think the original problem was that I had moved the table configurations from the default location to a different location.  Once I put the table definitions back to /tables, it started to update the schema on startup.  The logs above didn't show anything being added because the column had already been added; I deleted it again and redeployed and it started working.  The logs look like this now:

```
2017-03-12T16:41:19.656Z - �[32minfo�[39m: Updating schema for table User
2017-03-12T16:41:19.656Z - �[35msilly�[39m: Executing SQL statement SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @table AND TABLE_SCHEMA = @schema with parameters [{"name":"table","value":"User"},{"name":"schema","value":"dbo"}]
2017-03-12T16:41:19.671Z - �[35msilly�[39m: Executing SQL statement ALTER TABLE [dbo].[User] ADD [hasProfilePic] BIT NULL with parameters undefined
```

Thanks for your help; I'll close this issue now.

**Comment by danderson00** [comment]
Ahh OK, that could explain it. Make sure the location where your table definitions are stored matches the location that is being imported with the call to `mobileApp.tables.import`.

It sounds like you have things under control, anyway. Let us know if things don't work as you expect or we can help with anything else!
