### ISSUE TITLE
Support for async functions in APIs

### ISSUE THREAD

**Issue by sdsanders** [Azure/azure-mobile-apps-node#529]
For example:
```
module.exports.post = async (req, res) => {
    let results = await req.azureMobile.tables('tablename').where({
        id: req.body.id,
    }).read();

    res.json(results);
}
```
does not work. This is using native async/await that is now available as of node 7.6.0. It would seem that this is due to the type checking taking place when adding endpoints to the router during app startup. I would be happy to submit a PR!

**Comment by danderson00** [comment]
Very interesting! That would be awesome if you could submit a PR. Many thanks!

**Comment by ignaciofuentes** [comment]
Did support for this ever get added?

**Comment by sdsanders** [comment]
@ignaciofuentes my PR with this feature was merged but it seems like the library was abandoned around the same time so a new release with the support added was never released. 😢
