### ISSUE TITLE
How to get ad user details ?

### ISSUE THREAD

**Issue by navneetccna** [Azure/azure-mobile-apps-node#530]
I successfully logged in with AD authentication and redirect to my API page (API page is given below)

I tried "req.azureMobile.user" and "req.user" but both are not returning user details.

I am trying this in desktop browsers

var azureStorage = require('azure-storage');
var azureMobileApps = require('azure-mobile-apps');

var api = {
    get: function (req, res, next) {
        res.status(200).send(req.azureMobile.user);
        // alternative code i tried
        // res.status(200).send(req.user);
    }
};
module.exports = api;

I also tried to follow custom-api-routing example but getting following message 
You must be logged in to use this application

But i already logged in using AD authentication.

**Comment by danderson00** [comment]
Hi @navneetccna, 

I recommend against using a browser for testing authentication. If you are hitting the API endpoint directly, you need to manually attach the appropriate authorization headers (either `Authorization` or `x-zumo-auth`) that contain your auth token. Postman is a good utility for testing in this way.

I would test this by actually creating an instance of the Mobile Apps client, calling the `login` function, and then calling `invokeApi` to call into your custom API. That way, the Mobile Apps client will implicitly attach your authentication token to the request.

Keep in mind that if you're looking for additional user information, i.e. claims that the identity provider (e.g. facebook) return, you need to make an additional call to the `/.auth/me` endpoint, as described [here](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/authorization/). Note that the code is C#, but it should be straightforward to translate into Javascript.

Hope this makes sense! Let us know if we can be of further assistance.

**Comment by navneetccna** [comment]
Thanks for your response, but I want to use this on my web i want to create an admin section where user can see some reports. Is this suitable for this purpose (for web development) or what will be the alternative?

**Comment by adrianhall** [comment]
Azure Mobile Apps is primarily a mobile solution.  However, you can use it within an Express app.  In your case, you have to use the JS client (since it's a web app) to do the login - this will get you the appropriate token.  Then use fetch to fetch the /.auth/me endpoint - it returns JSON.  

Check out the following: https://shellmonger.com/2016/02/12/using-azure-app-service-authentication-with-a-web-application/
