### ISSUE TITLE
NH Tag value undefined not filtered on registration

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-node#531]
Hello!
On notifications/index.js, line 61. Added `typeof tag !== 'undefined'` because for some reason I got one undefined tag :S, maybe it's a small bug in other place on azure NH, or somewhere in my code, who knows, but adding this fixes the undefined tag since it filters it.
```

 function addUserTag(tags, userId) {
        if (userId) {
            tags = tags.filter(function (tag) {
                return typeof tag !== 'undefined' && !(tag && tag.indexOf(UserIdTagPrefix) === 0);
            });
            tags.push(UserIdTagPrefix + userId);
        }
        return tags;
    }
```

**Comment by danderson00** [comment]
Thanks for reporting this. The logic in the `if` expression is incorrect in the SDK - it should be:

    return tag && tag.indexOf(UserIdTagPrefix) !== 0

We'll get this fixed and do a patch release soon. Thanks again!

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/779ef2202635ef5899b6de5e5eee5b6d910be1df. We'll release a new version shortly.

**Comment by andreujuanc** [comment]
Cheers!
