### ISSUE TITLE
No error on incorrect column type name

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-node#532]
As title suggest, I made a mistake and wrote 'data' instead of 'date' and there was no error.

Is there any plans to support this? Or data is a valid type?

Cheers

**Comment by adrianhall** [comment]
Data is not a valid type.  We should have thrown an error on this.

Could you copy in your table definition so we have a complete repro?

**Comment by andreujuanc** [comment]
Sorry @adrianhall the bug exists, but not in this repo!! It's on the JS Client! 
Miscommunication with my coworker. Ill open it there.

Sorry!
