### ISSUE TITLE
Swagger UI is broken with latest version

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#536]
swagger-ui/dist/index.html no longer exists. I think the UI changed to a react app.

**Comment by danderson00** [comment]
With version 3.0, the package owners decided to exclude all but the core swagger-ui Javascript and CSS bundles, i.e. no other assets like index.html or images. This is [under review](https://github.com/swagger-api/swagger-ui/issues/2758).

For now, I intend to bundle the missing files directly into the azure-mobile-apps package using a git submodule. I will retain the existing behavior of needing to install the swagger-ui package before the UI will load.

**Comment by adrianhall** [comment]
Please ensure you add a section to README.md on enabling Swagger.  k-thx-bai

**Comment by danderson00** [comment]
The API to enable is the same, no changes. It might be a little out of place in the readme, but I can still add it.

**Comment by SteveALee** [comment]
I'm just checking if my problem is the same as it's not clear what the exact issue is here.

When I visit the API / Swagger tab in the new portal all is fine until I created. Now, whenever I select the tab I get taken back to my home dashboard.

**Comment by adrianhall** [comment]
Not the same issue, @SteveALee - this is for Azure Mobile Apps, not Functions.

**Comment by SteveALee** [comment]
Only wondered if problem in shared dependency
