### ISSUE TITLE
catch error and unhandledRejection

### ISSUE THREAD

**Issue by rytyr** [Azure/azure-mobile-apps-node#540]
I'm looking on how to catch error exception and unhandledRejection globally. 
This useful for catching bugs in production, probably with bugsnag or sentry.io 

The problem is, all API defined in **api** folder `mobile.api.import('./api')` never get caught.

In common express app, it is simply using this snippet
```javascript
app.use(function(err, req, res, next) {
    console.log('this is error');
});
process.on('unhandledRejection', function (reason) {
    console.log('this is rejection');
    throw reason;
});
```

Are there any other ways to catch both? Can't get any information around.
Thanks

**Comment by adrianhall** [comment]
You can always forego the mobile.api.import() and just create a normal express route.  That will do what you want.

**Comment by rytyr** [comment]
thanks for the suggestions.
could you describes what are the drawbacks of using normal express route instrad of the api imports?

**Comment by adrianhall** [comment]
In the custom API, the SDK decodes the user and provides the user, an instantiated data provider and an instantiated NH connection for you.  Those may not be available, depending on where you hook into the express pipeline.
