### ISSUE TITLE
Handling Concurrency/Status 412 when catching error from operations

### ISSUE THREAD

**Issue by mikejohanson** [Azure/azure-mobile-apps-node#541]
Hey Guys,

I've noticed when I started adding some error handlers around operations, I need to re-craft some responses that normally, when left unhandled, are generated by the SDK . For example, take the following code
```
table.delete(function (context) {
  client.trackEvent('DeletedEvent')
  return context.tables('Notes').update({ id: context.id, deletedDate: new Date(), deleted: true }).catch((err) => {
    client.trackException(err)
    return err
  })
})
```
The value for `err` for when there is a version conflict is something like: 
```
   { Error: No records were updated
    at Object.target.(anonymous function) [as concurrency] (/node_modules/azure-mobile-apps/src/utilities/errors.js:12:21)
    at Object.checkConcurrencyAndTranslate (/node_modules/azure-mobile-apps/src/data/mssql/statements/helpers.js:56:32)
    at Object.transform (/node_modules/azure-mobile-apps/src/data/mssql/statements/update.js:46:39)
    at /node_modules/azure-mobile-apps/src/data/mssql/execute.js:44:56
    at process._tickCallback (internal/process/next_tick.js:109:7)
  concurrency: true,
  item: 
   { id: '1',
     updatedAt: 2017-05-08T07:07:01.595Z,
     version: 'AAAAAAAIV5A=',
     note: 'A NOTE',
     deletedDate: null,
     createdAt: 2015-01-12T05:58:27.281Z,
     deleted: false } }
```
This lets me know that there was an issue, but what I'd like to be able to do is leverage what the SDK is doing in the [handleError.js](https://github.com/Azure/azure-mobile-apps-node/blob/master/src/express/middleware/handleError.js#L17)  file. Such that from this error, I can create the same response that a mobile or web app would expect. In other words, return the same response you would as if I didn't handle the error at all. How would I go about doing that?

I tried something like: 
```
var errMiddleware = require('../node_modules/azure-mobile-apps/src/express/middleware/handleError.js')
table.delete.use(table.operation, errMiddleware)

```
but that didnt seem to do the trick.  Appreciate the help, thanks!

**Comment by elamalani** [comment]
@mikejohanson Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-node#future-of-azure-mobile-apps).

I'll close this issue as its a year old but let us know if you have any questions. Thanks!
