### ISSUE TITLE
How to execute in query

### ISSUE THREAD

**Issue by navneetccna** [Azure/azure-mobile-apps-node#542]
My query like this

`
var query = {
    sql: "SELECT * FROM table WHERE type IN ('@value')",
    parameters: [
        {name: 'values', value: "a,b,c"}
    ]
};
`

can you please show the way to use in clause with parameterized  query ?

**Comment by elamalani** [comment]
@navneetccna Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps).

I'll close this issue as its a year old but let us know if you have any questions. Thanks!
