### ISSUE TITLE
JWT token validation fails due to invalid key

### ISSUE THREAD

**Issue by davidyee** [Azure/azure-mobile-apps-node#543]
In versions 4.0.0 and later, [verification](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) of JWT tokens fails. By stepping through the code, I found that in line 18 of [src/auth/index.js](https://github.com/Azure/azure-mobile-apps-node/blob/472dac053a7c431ef86cc8a03c3d46ddd8c22cce/src/auth/index.js#L18), the key is now based on the presence of `configuration.azureSigningKey` after which the key used in JWT verification is the result of the `hexStringToBuffer(configuration.azureSigningKey)`; otherwise, the plain `configuration.secret` string is used.

Normally, I suppose this behaviour would be fine; however, if the environment variable `WEBSITE_AUTH_SIGNING_KEY` is used to specify the `configuration.secret` string key, `configuration.auth.azureSigningKey` will also receive a copy of this value (see [line 109 of environment.js](https://github.com/Azure/azure-mobile-apps-node/blob/472dac053a7c431ef86cc8a03c3d46ddd8c22cce/src/configuration/from/environment.js#L109)). As a result, when [`jwt.verify` is called](https://github.com/Azure/azure-mobile-apps-node/blob/472dac053a7c431ef86cc8a03c3d46ddd8c22cce/src/auth/index.js#L39) it will use the result of `hexStringToBuffer` instead of the plain secret string in `configuration.secret`.

While the documentation for [`jwt.verify`](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) suggest that the key can be string or buffer, when I run my Mobile App with this change in v4.0.0 or later, the JWT verification fails and returns a 401 error code on my API endpoints that require authentication. These APIs return the following response despite a valid JWT specified in the `Authorization` header:

```json
{
"name": "JsonWebTokenError",
"message": "invalid signature"
}
```

For your reference, these changes are documented in [this git diff](https://github.com/Azure/azure-mobile-apps-node/commit/472dac053a7c431ef86cc8a03c3d46ddd8c22cce#diff-2b0a2893c010a4aea8147a48a8fdd092).

Is this change in behaviour between v3 and v4 documented somewhere or is it a bug?

**Comment by elamalani** [comment]
@davidyee Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-node#future-of-azure-mobile-apps). At this time, we will only look at fixing critical issues in the product. 

I'll close this issue for now but let us know if you have any questions. Thanks!
