### ISSUE TITLE
Server SDK not working with Android SDK when use include total count

### ISSUE THREAD

**Issue by educosta** [Azure/azure-mobile-apps-node#544]
Hi,

After server SDK version 2.1.7 when I trying use includeTotalCount() on Android SDK, don't returning results.

Thanks

**Comment by elamalani** [comment]
@navneetccna Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-node#future-of-azure-mobile-apps).

Are you still running into this issue? I'll close this issue as its a year old but let us know if you have any questions. Thanks!
