### ISSUE TITLE
How to connect to Mobile App Service backend on MacOS?

### ISSUE THREAD

**Issue by grai001** [Azure/azure-mobile-apps-node#547]
The readme displays these steps:

> Create a server.js file and add the following code to the file (or use the code from one of our samples):
> 
> ```
> var app = require('express')(); // Create an instance of an Express app
> var mobileApp = require('azure-mobile-apps')(); // Create an instance of a Mobile App with default settings
> 
> mobileApp.tables.add('TodoItem'); // Create a table for 'TodoItem' with default settings
> 
> app.use(mobileApp);
> app.listen(process.env.PORT || 3000);
> ```
>
> Run your project locally with `node server.js`

Then it instructs: 

> For steps 4-5, you can use any of the clients found in the Client & Server Quickstarts to test.

But the readme in that link states: "Prerequisites .NET 4.0 Framework". I am using a mac. How can I connect to the backend on a MacOS?

**Comment by erichedstrom** [comment]
Did you try running it on MacOS? The .Net 4.0 framework is for the C# backend, not this Node.js one.
