### ISSUE TITLE
Bug: incorrect implementation of JWT validation for audiences and issuers

### ISSUE THREAD

**Issue by trevorfrese** [Azure/azure-mobile-apps-node#549]
Hi,

There is a bug in how the audience and issuers are generated for azure mobile apps:
https://github.com/Azure/azure-mobile-apps-node/blob/master/src/configuration/from/environment.js#L99

As you can see, the audience is being set to *a string value* instead of an *array*. 

This is limiting the number of acceptable hostnames for an app service to exactly 1. Our web app has 2 hostnames that should be allowed. If you dig into the jsonwebtoken library you see that the verification is against an *array*:
https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js#L130-L138

A solution is to replace the string assignment with:
```
                configuration.auth.audience.push('https://' + environment[key] + '/');
                configuration.auth.issuer.push('https://' + environment[key] + '/');
``` 

But more so than this, there needs to be a larger modification to configure the audiences to actually grab the hostnames from the "Custom Hostnames" or the "allowed audiences" object, but I'm not exactly sure where azure is storing these in the environment.

**Comment by elamalani** [comment]
@trevorfrese Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-node#future-of-azure-mobile-apps). At this time, we will only look at fixing critical issues in the product. 

I'll close this issue for now but let us know if you have any questions. Thanks!
