### ISSUE TITLE
Run integration tests using q as promise library

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#55]

**Comment by danderson00** [comment]
This could be tricky. The alternate promise library needs to be specified in the configuration, which we recreate in each test suite. I was thinking to just run a subset of the express integration tests with alternate promises, perhaps just the end to end.

**Comment by danderson00** [comment]
@mamaso Can you add another test run to jenkins to run the test suite with q? Cheers!

**Comment by danderson00** [comment]
I'll do this as part of #295

**Comment by mamaso** [comment]
ok cool, thanks.  This keeps slipping my mind

**Comment by danderson00** [comment]
Unit tests are now run with Q promises as part of the build
