### ISSUE TITLE
Support for other SQL data types (BigInt, Decimal ...)

### ISSUE THREAD

**Issue by Magurosenbei** [Azure/azure-mobile-apps-node#550]
Hello,

The current implementation does not recognize bigint, decimals and other sql data types as a valid column type. So if your existing tables contains bigint and such, you will encounter things like 'Unrecognised column type' time to time.

For now I have modified the package's mssql helper `getPredefinedColumnType` to return its argument as-is on default switch case to by pass the 'Unrecognised column type: ' error thrown to suite my needs.
https://github.com/Azure/azure-mobile-apps-node/blob/master/src/data/mssql/helpers.js

Is there a better way to override that behavior other than modifying directly from the package contents installed by npm?

**Comment by elamalani** [comment]
@Magurosenbei Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-node#future-of-azure-mobile-apps). At this time, we will only look at fixing critical issues in the product. 

I'll close this issue for now but let us know if you have any questions. Thanks!
