### ISSUE TITLE
is there any provision to define the NOTNULL constraint for columns

### ISSUE THREAD

**Issue by ajeeshadressary** [Azure/azure-mobile-apps-node#554]
table.dynamicSchema = false;

table.columns = {
    firstName: 'string',
    lastName: 'string',
    userName: 'string',
    description: 'string',
    email: 'string',
    authId: 'string',
    authProvider: 'string',
    hasProfilePic: 'boolean'
};

table.databaseTableName = 'User';

table.read.access = 'anonymous';
table.insert.access = 'authenticated';
table.update.access = 'authenticated';
table.delete.access = 'disabled';

**Comment by adrianhall** [comment]
There isn't.  The best way to do this is to run the server to create the table, then use ALTER TABLE to define the NOTNULL constraint.
