### ISSUE TITLE
How to do custom username and password Authentication using Azure Mobile App Services ??

### ISSUE THREAD

**Issue by kkadapa** [Azure/azure-mobile-apps-node#555]
I am terribly in need of Authenticating users based on simple username and password rather than AD, FB, Twitter which are the sole options via Azure Mobile App. I just want to check the users table that i have in SQL Server database and authenticate them. Would you be able to help me with that? I have my user table like this in Node.js. How do i check this table for users and Authenticate?

I don't know if it's possible

NSDictionary *tokenDict = @{@"uniqueId": @"ntuser"};
    [client loginWithProvider:@"auth" token:tokenDict completion:^(MSUser * _Nullable user, NSError * _Nullable error) {
        
        if (error) {
            NSLog(@"error during login is %@",error);
        }else {
            
            NSLog(@"user is %@",user);
            NSLog(@"userID is %@",user.userId);
            NSLog(@"mobileServiceAuthenticationToken); is %@",user.mobileServiceAuthenticationToken);
        }        
    }];
}

usertable.json
{
	  "softDelete" : true,
	  "autoIncrement": false,
  "insert": {
    "access": "authenticated"
  },
  "update": {
    "access": "authenticated"
  },
  "delete": {
    "access": "authenticated"
  },
  "read": {
    "access": "authenticated"
  },
  "undelete": {
    "access": "authenticated"
  }}

usertable.js
var table = module.exports = require('azure-mobile-apps').table();

// table.read(function (context) {
//     return context.execute();
// });

// table.read.use(customMiddleware, table.operation);
// Ensure that only records for the authenticated user are retrieved.

**Comment by jwallra** [comment]
Hi @kkadapa, please check out our [sample](https://github.com/Azure/azure-mobile-apps-node/tree/master/samples/custom-authentication) which provides an implementation of custom authentication.  Let us know if you have any questions about it!

**Comment by kkadapa** [comment]
Thank you very much @jwallra. I wrote the node.js code to verify the user in my database. However, the client code is throwing this exception 

```
NSDictionary *tokenDict = @{@"userid": @"ntuser511"};
    [client loginWithProvider:@"auth" token:tokenDict completion:^(MSUser * _Nullable user, NSError * _Nullable error) {
        
        if (error) {
            NSLog(@"error during login is %@",error);
        }else {
            
            NSLog(@"user is %@",user);
            NSLog(@"userID is %@",user.userId);
            NSLog(@"mobileServiceAuthenticationToken); is %@",user.mobileServiceAuthenticationToken);
        }
    }];
```

**error during login is Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 "Cannot POST /.auth/login/auth
" UserInfo={NSLocalizedDescription=Cannot POST /.auth/login/auth
}**

**Comment by jwallra** [comment]
`loginWithProvider` won't work with custom auth.  It looks like you don't have a `/.auth/login/auth` API endpoint on your app.  You can create those through the azure portal by adding an "Easy API" and using it as a custom auth endpoint.  We have some more custom auth documentation [here](https://adrianhall.gitlab.io/develop-mobile-apps-with-csharp-and-azure/chapter2/custom/) which may give you more insight.

I'll be here to answer any more questions :)

**Comment by kkadapa** [comment]
Thank you very much @jwallra i changed my requirement and mandated uname & pwd. You are super responsive. I did a lot of progress in the past few days. I also opened a ticket on the raining cloud and i believe that is going to being resolved soon. Lastly i want to let you know about the bcrypt issue from the [sample](https://github.com/Azure/azure-mobile-apps-node/tree/master/samples/custom-authentication) you shared... it is having issues with node modules (please try to reproduce it yourself) and the work around is to use [bcrypt-nodejs](https://www.npmjs.com/package/bcrypt-nodejs). I wish there is some kind of documentation within the Azure Mobile App page for Custom Auth like Firebase in future. You may close this issue now 👍

**Comment by jwallra** [comment]
@kkadapa We have documentation on how to use tokens [here](https://adrianhall.gitlab.io/develop-mobile-apps-with-csharp-and-azure/chapter2/realworld/).  Since you're using custom auth, you should decide the expiration of the token and if you want to use refresh tokens.  The documentation should help you with that.

Thanks for the feedback on documentation, we'll take note for the future for how we can improve the service.
