### ISSUE TITLE
Unexpected connection failure

### ISSUE THREAD

**Issue by abhishek3999** [Azure/azure-mobile-apps-node#557]
*Used below code snippet:*
`this.client.push.register(
  'gcm', 
  data.registrationId, 
  {
    mytemplate: { body: { data: { message: "{$(messageParam)}" } } }
  }, 
  null, 
  function(error, response) {
    if (error) {
      console.error('Error registering for pushes: ' + error);
    } else {
      console.log('Registering for pushes response: ' + response.statusText);
    }
  }
);`
What would be right so that I can solve this error?
Am trying to implement push notification using ionic3

**Comment by ElektrojungeMS** [comment]
Hey @abhishek3999,

Thanks for getting in touch. I see that you already filed an issue for the [js client](https://github.com/Azure/azure-mobile-apps-js-client/issues/284). I'm closing this issue, let's continue the discussion at the original issue to make sure we don't loose context.

**Comment by abhishek3999** [comment]
Okay.No issues.
