### ISSUE TITLE
Normalize user identity properties that are returned from the gateway

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#65]
Provide a standard user identity field no matter what IdP is being used from the gateway (facebook, twitter, google, mso, aad)

**Comment by phvannor** [comment]
Is this applicable to Easy Auth?  What has happened to the user ids from the v1 enhanced users opt in feature?

**Comment by danderson00** [comment]
@phvannor This is about normalising the set of properties returned from a call to getIdentities. The article you provided about the feature in question (http://blogs.msdn.com/b/carlosfigueira/archive/2013/12/16/enhanced-users-feature-in-azure-mobile-services.aspx) does not show any properties normalised.

I'm not sure what you're asking?

**Comment by phvannor** [comment]
Seperating in two, with Easy Auth, we should at least rename this issue since there is no Gateway.

**Comment by danderson00** [comment]
V1 did not provide this functionality, value is questionable. Closing for now.
