### ISSUE TITLE
Support swagger for provided endpoints

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#68]

**Comment by phvannor** [comment]
This will also need to be worked into our more general plans for exposing metadata (so clients can work with an Id, Version, etc column and endpoints for syncing as well)

**Comment by danderson00** [comment]
For tables, this is fairly simple. For custom APIs, it requires introducing user configuration to specify response schemas, etc. We can probably get away with just tables for GA.
