### ISSUE TITLE
Provide integration tests for ensuring optimistic concurrency works on soft delete / undelete

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#76]

**Comment by danderson00** [comment]
One test for delete added in https://github.com/Azure/azure-mobile-apps-node/commit/3041c0c65ef91fd49a29ca1f42c6d0ad1256ba63

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/36090f48be247d09e0035c85d3dfc3f82c27af5a
