### ISSUE TITLE
Make returning stuff from operation scripts easy

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#79]
Current advice is to return results to client  via res.send() but it would be better if we could just return results directly.  (Why?)

**Comment by adrianhall** [comment]
Dale - please add info on why you would res.send()/res.json() and why not?  Maybe we can just close this?

**Comment by danderson00** [comment]
It is not recommended to return results to the client using res.json or res.send as this will impact batching when this is implemented down the track. The guideline is to return results from the final step in the promise chain. Closing.
