### ISSUE TITLE
Query objects should be immutable

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#82]
queryjs - all operations affect the same object

**Comment by phvannor** [comment]
Is this the QueryJS implementation, or wrappers in the Node SDK?  If the former, the issue should be moved over there.

**Comment by danderson00** [comment]
Yeh, it is actually queryjs. This change is a breaking change as well, needs to be done carefully.

**Comment by phvannor** [comment]
Right esp as I think the cordova work is now just using head?  Are we sure that we want this to be immutable there as well?
