### ISSUE TITLE
Implement require HTTPS

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#94]
Remember that Azure Web Apps handles ssl termination, i.e. the app will always receive http requests even if the client requests using https.

**Comment by adrianhall** [comment]
If the two scenarios supported are "test' and "aure web apps", why do we need to support HTTPS?

**Comment by danderson00** [comment]
We aren't "supporting" https, we're enforcing the usage of HTTPS. Hopefully, we can do this using web.config and simply provide guidance, but in V1, we actually added some code.

**Comment by adrianhall** [comment]
Handled by Azure App Service already.

**Comment by educosta** [comment]
Hi,

How can I force https on my app?

Thank you!

**Comment by danderson00** [comment]
Hi @educosta, since we use iisnode, you should be able to use web.config to force a redirect to HTTPS. Have a look at http://stackoverflow.com/questions/9823010/how-to-force-https-using-a-web-config-file.

Not sure if there is an option within the Azure portal to do this, @adrianhall? Turning on Authentication / Authorization forces HTTPS, so you could turn it on and let anonymous requests through, but that's a bit of a hack.

**Comment by educosta** [comment]
Thank you very much! Both solutions works!
