### ISSUE TITLE
Enhance support for OData with Navigation Properties and $expand

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-node#95]
Richer support for OData would avoid the need to write server side API scripts for queries that involve joining related tables. OData supports this by expressing queries that navigate over the graph of related entities. [OData 2 $expand](http://www.odata.org/documentation/odata-version-2-0/uri-conventions)

**Comment by danderson00** [comment]
Duplicate of https://github.com/Azure/azure-mobile-apps-node/issues/455
