### ISSUE TITLE
Support multi-level paths in custom APIs

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#96]
Enhance the custom API implementation by allowing multi level paths in API modules, e.g.:
```
module.exports = {
    add: {
        get: function (req, res, next) { }
    },
   subtract: {
        get: function (req, res, next) { }
    }
}

**Comment by adrianhall** [comment]
See also #178

**Comment by mamaso** [comment]
See also #350

**Comment by danderson00** [comment]
Unfortunately, we won't be adding this feature, given how easy it is to mount express routers to achieve the same functionality and taking into account plans.
